--######################################################################################
-- View For Transaction
--
-- MEMBER_NAME     : Cluster Member Name
-- USER_NAME       : User Name
-- USER_ID         : Session Identifier
-- USER_SERIAL     : Session Serial
-- CHARSET         : Session Charset
-- PROGRAM         : Program Name
-- USER_LOGIN_TIME : User Login Time
-- TRANSACTION_ID  : Transaction Identifier
-- TRAN_BEGIN_TIME : Transaction Begin Time
--
--gSQL> SELECT * FROM TECH_TRANSACTION;
--
--MEMBER_NAME USER_NAME USER_ID USER_SERIAL CHARSET PROGRAM USER_LOGIN_TIME            TRANSACTION_ID TRAN_BEGIN_TIME           
------------- --------- ------- ----------- ------- ------- -------------------------- -------------- --------------------------
--G1N1        SYS             4           1 UTF8    gsql    2018-08-08 15:26:42.502763       33292292 2018-08-08 15:55:23.107324
--######################################################################################

DROP VIEW IF EXISTS PERFORMANCE_VIEW_SCHEMA.TECH_TRANSACTION;

CREATE VIEW PERFORMANCE_VIEW_SCHEMA.TECH_TRANSACTION
(
  MEMBER_NAME,
  USER_NAME,
  USER_ID,
  USER_SERIAL,
  CHARSET,
  PROGRAM,
  USER_LOGIN_TIME,
  TRANSACTION_ID,
  TRAN_BEGIN_TIME
)
AS
SELECT
  NVL(XT.CLUSTER_MEMBER_NAME, 'STANDALONE') MEMBER_NAME,
  AU.AUTHORIZATION_NAME USER_NAME,
  XS.ID USER_ID,
  XS.SERIAL USER_SERIAL,
  XS.CLIENT_CHARSET CHARSET,
  XS.PROGRAM PROGRAM,
  XS.LOGON_TIME USER_LOGIN_TIME,
  XT.LOGICAL_TRANS_ID TRANSACTION_ID,
  XT.BEGIN_TIME TRAN_BEGIN_TIME
FROM
  AUTHORIZATIONS@GLOBAL[IGNORE_INACTIVE_MEMBER] AU,
  X$TRANSACTION@GLOBAL[IGNORE_INACTIVE_MEMBER] XT,
  X$SESSION@GLOBAL[IGNORE_INACTIVE_MEMBER] XS
WHERE
  1 = 1 AND
  NVL(AU.CLUSTER_MEMBER_NAME, 'STANDALONE') = NVL(XT.CLUSTER_MEMBER_NAME, 'STANDALONE') AND
  NVL(AU.CLUSTER_MEMBER_NAME, 'STANDALONE') = NVL(XS.CLUSTER_MEMBER_NAME, 'STANDALONE') AND
  NVL(XT.CLUSTER_MEMBER_NAME, 'STANDALONE') = NVL(XS.CLUSTER_MEMBER_NAME, 'STANDALONE') AND
  AU.AUTH_ID = XS.USER_ID AND
  XT.LOGICAL_TRANS_ID = XS.TRANS_ID AND
  XT.DRIVER_MEMBER_ID != -1 ;
  
GRANT SELECT ON TABLE PERFORMANCE_VIEW_SCHEMA.TECH_TRANSACTION TO PUBLIC;