ERROR_CODE SQL_STATE MESSAGE
---------- --------- -----------------------------------------------
     11000     HY000 Invalid argument
     11001     HY000 The operation was incomplete although some processing was performed and the results are partially valid
     11002     HY000 Permission denied '%s'
     11003     HY000 Standard layer has encountered the end of the file
     11004     HY000 Unable to duplicate a file
     11005     HY000 File lock error
     11006     HY000 File unlock error
     11007     HY000 Unable to open the file '%s'
     11008     HY000 Unable to close the file
     11009     HY000 Unable to remove the file
     11010     HY000 Unable to link the file
     11011     HY000 Unable to read the file
     11012     HY000 Unable to write the file
     11013     HY000 Unable to sync the file
     11014     HY000 Unable to seek the file
     11015     HY000 Unable to truncate the file
     11016     HY000 Unable to get the status of the file
     11017     HY000 Unable to create a pipe
     11018     HY000 Unable to wait for the given process
     11019     HY000 Insufficient resource
     11020     HY000 Unable to send signal to given process
     11021     HY000 Unable to set a signal handler
     11022     HY000 Unable to block a signal
     11023     HY000 Unable to set thread attribute
     11024     HY000 Unable to create a thread
     11025     HY000 Unable to join with a terminated thread
     11026     HY000 Unable to set thread once code
     11027     HY000 Truncation occurred on I/O operation
     11028     HY000 The given name(%s) is too long
     11029     HY000 shared memory segment exists
     11030     HY000 Unable to allocate a shared memory segment
     11031     HY000 Unable to attach the shared memory segment
     11032     HY000 Unable to detach the shared memory segment
     11033     HY000 Unable to destroy the shared memory segment
     11034     HY000 Unable to create a semaphore
     11035     HY000 Unable to acquire the given semaphore
     11036     HY000 Unable to release the given semaphore
     11037     HY000 Unable to destroy the given semaphore
     11038     HY000 The given object was busy
     11039     HY000 Operation timed out
     11040     HY000 No such object (%s)
     11041     HY000 Two objects do not match
     11042     HY000 Not enough memory
     11043     HY000 File system is full
     11044     HY000 Unable to execute the program
     11045     HY000 not supported function
     11046     HY000 given buffer does not have enough space
     11047     HY000 invalid network address
     11048     HY000 sendto() system call returned failure
     11049     HY000 recvfrom() system call returned failure
     11050     HY000 failed to get address from socket with getsockname()
     11051     HY000 failed to get peer address from socket with getpeername()
     11052     HY000 failed to manipulate file descriptor with fcntl()
     11053     HY000 failed to manipulate socket descriptor with setsockopt()
     11054     HY000 not implemented feature
     11055     HY000 failed to manipulate device parameters of special file with ioctl()
     11056     HY000 failed to get hostname
     11057     HY000 failed to close a socket
     11058     HY000 failed to shutdown a socket
     11059     HY000 failed to create a socket
     11060     HY000 failed to get property of a file descriptor
     11061     HY000 failed to set property of a file descriptor
     11062     HY000 failed to bind a socket to address
     11063     HY000 failed to listen on a socket
     11064     HY000 failed to accept a connection request with a socket
     11065     HY000 system call was interrupted by a signal
     11066     HY000 failed to get options of a socket
     11067     HY000 failed to connect to an host with a socket
     11068     HY000 failed to wait for some file descriptors with poll()
     11069     HY000 internal error
     11070     HY000 sendmsg() system call returned failure
     11071     HY000 recvmsg() system call returned failure
     11072     HY000 socketpair() system call returned failure
     11073     HY000 converted value is out of range (overflow or underflow)
     11074     HY000 given string is not number
     11075     HY000 invalid file desciptor
     11076     HY000 resource temporarily unavailable
     11077     HY000 given address is already in use
     11078     HY000 failed to initialize communication context
     11079     HY000 failed to finalize communication context
     11080     HY000 failed to connect communication context
     11081     HY000 failed to poll communication context
     11082     HY000 failed to write packet through communication context
     11083     HY000 failed to read packet through communication context
     11084     HY000 failed to send descriptor through communication context
     11085     HY000 failed to receive descriptor through communication context
     11086     HY000 failed to get current file path
     11087     HY000 failed to open library (%s)
     11088     HY000 failed to close library
     11089     HY000 failed to get symbol address (%s)
     11090     HY000 not supported query
     11091     HY000 failed to check file (%s)
     11092     HY000 input is too long
     11093     HY000 system call error (function : %s, error no : %d)
     11094     HY000 divide zero
     11095     HY000 Unable to open a semaphore
     11096     HY000 Unable to close the given semaphore
     11097     HY000 Unable to unlink the given semaphore
     11098     HY000 permission denied - '%s'
     11099     HY000 not supported os
     11100     HY000 Environment variable "%s" is not defined.
     11101     HY000 License file(%s) does not exist
     11102     HY000 License is out of date. License is valid after %4d-%02d-%02d
     11103     HY000 License date is expired. License is expired in %4d-%02d-%02d
     11104     HY000 License core count mismatch.
     11105     HY000 License key is corrupted.
     11106     HY000 License host name mismatch.
     11107     HY000 failed to set thread affinity.
     11108     HY000 failed to create timer.
     11109     HY000 failed to set timer.
     11110     HY000 failed to destroy timer.
     11111     HY000 address is not given.
     11112     HY000 Unable to access the message queue.
     11113     HY000 A message queue exists.
     11114     HY000 Unable to create a message queue.
     11115     HY000 The message queue was removed.
     11116     HY000 Unable to destroy the message queue.
     11117     HY000 Unable to send message.
     11118     HY000 Unable to receive message.
     11119     HY000 No message was available in the message queue.
     11120     HY000 failed to get property of a file status
     11121     HY000 failed to set property of a file status
     11122     HY000 infiniband ibv/rdma interface returned error
     11123     HY000 no infiniband device was found
     11124     HY000 cannot find specified infiniband device
     11125     HY000 cannot find suitable Memory Region for specified ptr and size
     11126     HY000 failed to get semaphore value
     11127     HY000 failed to control pollset
     11128     HY000 failed to create pollset
     11129     HY000 overflow fd
     11130     HY000 invalid INI file format
     11131     HY000 path '%s' does not exist
     11132     HY000 Unable to get maximum undo semaphores per array
     11133     HY000 Unable to create a undo semaphore
     11134     HY000 Unable to bind the given undo semaphore
     11135     HY000 Unable to unbind the given undo semaphore
     11136     HY000 Unable to get the given undo semaphore state
     11137     HY000 Unable to destroy the given undo semaphore
     11138     HY000 Unable to suspend asyncronous io
     11139     HY000 Unable to control the shared memory segment
     11140     HY000 Unable to detach a thread
     11141     08S01 Communication link failure
     11142     HY000 No such process
     12000     HY000 failed to initialize datatype layer
     12001     HYC00 not implemented feature, in a function %s
     12002     22001 byte length of data greater than column length
     12003     22001 character length of data greater than column length
     12004     22001 data converted with truncation of fractional digits
     12005     22001 conversion of data would result in loss of whole digits
     12006     22018 data value is not a numeric literal
     12007     22003 data is outside the range of the data type to which the number is being converted
     12008     22001 data is greater than 0, less than 2, and not equal to 1
     12009     22003 data is less than 0 or greater than or equal to 2
     12010     22001 (byte length of data)/2 is greater than column byte length
     12011     22003 data value is not a hexadecimal value
     12012     22008 data value is a valid timestamp literal; time portion is nonzero
     12013     22018 data value is not a valid date literal or timestamp literal
     12014     22008 data value is a valid timestamp literal; fractional seconds portion is nonzero
     12015     22018 data value is not a valid time literal or timestamp literal
     12016     22008 data value is a valid timestamp literal; fractional seconds portion truncated
     12017     22018 data value is not a valid date literal or time literal or timestamp literal
     12018     22015 data value is a valid interval value; the value in one of the fields is truncated
     12019     22018 data value is not a valid interval literal
     12020     22001 number of digits greater than column byte length
     12021     22001 number of characters greater than column byte length
     12022     22003 data converted with truncation of whole digits
     12023     22003 data is outside the range of the data type to which the number is being converted
     12024     22001 data is greater than 0, less than 2, and not equal to 1
     12025     22003 data is less than 0 or greater than or equal to 2
     12026     22015 interval data truncated
     12027     22001 byte length of data greater than column length
     12028     22001 character length of data greater than column length
     12029     22003 byte length of data not equal to SQL data length
     12030     22001 column byte length is less than %d
     12031     22008 data value is not a valid date
     12032     22007 data value is not a valid date format
     12033     22001 column byte length is less than %d
     12034     22018 data value is not a valid GUID
     12035     22001 column byte length is less than %d
     12036     22001 data value is not a valid time
     12037     22007 data value is not a valid time format
     12038     22001 column byte length is between %d and character byte length
     12039     22001 column byte length is less than %d
     12040     22008 data value is not a valid timestamp
     12041     22008 time fields are nonzero
     12042     22007 data value does not contain a valid date
     12043     22008 fractional seconds fields are nonzero
     12044     22007 data value does not contain a valid time
     12045     22008 fractional seconds fields are truncated
     12046     22007 data value does not contain a valid timestamp
     12047     22001 column byte length is less than character byte length
     12048     22015 data value is not a valid interval literal
     12049     22003 conversion resulted in truncation of whole digits
     12050     22015 one or more fields of data value were truncated during conversion
     12051     22001 column byte length is less than character byte length
     12052     22015 data value is not a valid interval literal
     12053     22003 conversion resulted in truncation of whole digits
     12054     22015 one or more fields of data value were truncated during conversion
     12055     01004 byte length of data greater equal than buffer length
     12056     01004 character length of data greater equal than buffer length
     12057     01S07 data converted with truncation of fractional digits
     12058     22003 conversion of data would result in loss of whole digits
     12059     22018 data is not numeric literal
     12060     22003 data is outside the range of the data type to which the number is being converted
     12061     01S07 data is greater than 0, less than 2, and not equal to 1
     12062     22003 data is less than 0 or greater than or equal to 2
     12063     01S07 data value is a valid timestamp-value; time portion is nonzero
     12064     22018 data value is not a valid date-value or timestamp-value
     12065     01S07 data value is a valid timestamp-value; fractional seconds portion is nonzero
     12066     22018 data value is not a valid time-value or timestamp-value
     12067     22018 data value is not a valid date-value or time-value or timestamp-value
     12068     01S07 data value is a valid interval value;truncation of one or more trailing fields
     12069     22015 data value is a valid interval; leading field significant precision is lost
     12070     22018 data value is not a valid interval value
     12071     01004 number of whole digits is less than buffer length
     12072     22003 number of whole digits is greater than buffer length
     12073     01S07 data converted with truncation of fractional digits
     12074     22003 conversion of data would result in loss of whole digits
     12075     22003 data is outside the range of the data type to which the number is being converted
     12076     01S07 data is greater than 0, less than 2, and not equal to 1
     12077     22003 data is less than 0 or greater than or equal to 2
     12078     22003 byte length of data is greater than buffer length
     12079     01S07 fractional seconds portion truncated
     12080     22015 whole part of number truncated
     12081     22003 buffer length is less equal than 1
     12082     22003 buffer length is less than 1
     12083     01004 (byte length of data)/2 is greater equal than buffer length
     12084     01004 (character length of data)/2 is greater equal than buffer length
     12085     01004 byte length of data is greater than buffer length
     12086     01004 buffer length is between %d and character byte length
     12087     22003 buffer length is less than %d
     12088     22003 byte length of data is greater than buffer length
     12089     22003 buffer length is less than %d
     12090     22003 byte length of data is greater than buffer length
     12091     01004 buffer length is between %d and character byte length
     12092     22003 buffer length is less than %d
     12093     22003 byte length of data is greater than buffer length
     12094     01004 buffer length is between %d and character byte length
     12095     22003 buffer length is less than %d
     12096     01004 buffer length is between %d and character length
     12097     22003 byte length of data is greater than buffer length
     12098     01S07 time portion of timestamp is nonzero
     12099     01S07 fractional seconds portion of timestamp is nonzero
     12100     01S07 fractional seconds portion of timestamp is truncated
     12101     01S07 trailing fields portion truncated
     12102     22015 leading precision of target is not big enough to hold data from source
     12103     22003 interval precision was a single field and truncated whole
     12104     22015 interval precision was not a sigle field
     12105     22003 byte length of data is greater than buffer length
     12106     01004 number of whole digits is less than buffer length
     12107     22003 number of whole digits is greater equal than buffer length
     12108     01S07 trailing fields portion truncated
     12109     22015 leading precision of target is not big enough to hold data from source
     12110     01S07 interval precision was a single field and truncated fractional
     12111     22003 interval precision was a single field and truncated whole
     12112     07006 interval precision was not a sigle field
     12113     22003 byte length of data is greater than buffer length
     12114     01004 number of whole digits is less than buffer length
     12115     22003 number of whole digits is greater equal than buffer length
     12116     22009 invalid time zone displacement value
     12117     42000 invalid number of arguments
     12118     42000 inconsistent datatype of function parameters: %s
     12119     42000 comparison is not applicable: %s and %s
     12120     42000 conversion is not applicable: from %s to %s
     12121     22021 invalid character value in characterset repertoire
     12122     22012 divisor is equal to zero
     12123     22018 data is not boolean literal
     12124     HY000 invalid argument for factorial function
     12125     22027 trim set should have only one character
     12126     22008 datetime field overflow
     12127     HY000 invalid ROWID
     12128     22019 invalid escape character
     12129     HY000 invalid character set identifier
     12130     HY000 invalid extract field for extract source
     12131     42000 inconsistent datatypes: argument[%d] expected %s
     12132     HY000 date format value exceeds maximum length (%d)
     12133     HY000 date format not recognized
     12134     HY000 format code appears twice
     12135     HY000 %s conflicts with %s
     12136     HY000 literal does not match format string
     12137     HY000 input value not long enough for date format
     12138     HY000 date format picture ends before converting entire input string
     12139     HY000 year must be between %s and %s, and not be 0
     12140     2200C missing or illegal character following the escape character
     12141     HY000 not a valid month
     12142     HY000 a non-numeric character was found where a numeric was expected
     12143     HY000 day of month must be between 1 and last day of month
     12144     HY000 not a valid day of the week
     12145     HY000 day of year must be between 1 and 365 (366 for leap year)
     12146     HY000 format code cannot appear in date input format
     12147     HY000 BC/B.C. or AD/A.D. required
     12148     HY000 julian date must be between 0 and 5373484
     12149     HY000 %s may only be specified once
     12150     HY000 Julian date precludes use of day of year
     12151     HY000 Not enough format info buffer
     12152     HY000 hour must be between %d and %d
     12153     HY000 minute must be between 0 and 59
     12154     HY000 second must be between 0 and 59
     12155     HY000 the fractional seconds must be between 0 and 999999
     12156     HY000 time zone hour must be between -14 and 14
     12157     HY000 time zone minute must be between 0 and 59
     12158     HY000 seconds in day must be between 0 and 86399
     12159     HY000 AM/A.M. or PM/P.M. required
     12160     HY000 HH24 precludes use of meridian indicator
     12161     HY000 %s conflicts with use of %s
     12162     HY000 invalid XID string
     12163     HY000 date not valid for month specified
     12164     HY000 signed year precludes use of BC/AD
     12165     HY000 number format value exceeds maximum length (%d)
     12166     HY000 invalid number format model
     12167     HY000 cannot use %s twice
     12168     HY000 cannot use %s and %s together
     12169     22001 string data, right truncation
     12170     HY000 argument '%ld' is out of range
     12171     HY000 invalid datepart for data type %s
     12172     42000 maximum number of arguments exceeded
     12173     42000 invalid char length units(%s): use OCTETS or CHARACTERS
     12174     22023 The argument of %s function is invalid
     12175     22023 The argument [%d] of %s function is invalid
     12176     HY000 internal error, in a function %s
     12177     HY000 not supported data type ( %s )
     12178     HY000 data type specifier is out of range ( type : %d, range : %d to %d )
     12179     HY000 precision specifier is out of range( type : %s, precision : %ld, range : %ld to %ld )
     12180     HY000 leading precision specifier is out of range( type : %s, precision : %ld, range : %ld to %ld )
     12181     HY000 scale specifier is out of range( type : %s, scale : %ld, range : %ld to %ld )
     12182     HY000 fractional second precision specifier is out of range( type : %s, precision : %ld, range : %ld to %ld )
     12183     HY000 character length unit specifier is out of range( type : %s, character length unit : %d, range : %d to %d )
     12184     HY000 interval indicator specifier is out of range( type : %s, indicator : %d, range : %d to %d )
     12185     42000 %s and %s cannot be matched
     12186     0A000 not supported function %s
     12187     39000 failed to open customer built-in function library (%s)
     13000     HY000 Failed to initialize kernel layer
     13001     HY000 kernel layer is not initialized yet
     13002     HY000 Invalid argument
     13003     HY000 Invalid shared memory segment type
     13004     HY000 static shared memory segment is corrupted
     13005     HY000 maximum number of shared memory segment num exceeded
     13006     HY000 kernel layer internal error - %s
     13007     42000 identifier is too long
     13008     HY000 comment is too long
     13009     42S02 fixed table does not exist
     13010     HY000 Insufficient static area
     13011     HY000 Unable to extend memory: [MAX: %ld, TOTAL: %ld, USED: %ld, ALLOC: %d, REQUESTOR: %d] DESC: %s
     13012     HY000 too many files are opened
     13013     HY000 Property(%s) does not exist
     13014     HY000 Unable to change property at this startup phase.(%s)
     13015     0U000 Unable to change read-only property.(%s)
     13016     22000 Invalid property value.(%s)
     13017     0U000 Specified property cannot be modified using ALTER SESSION.(%s)
     13018     22000 Specified property cannot be modified with this SCOPE option.(%s)
     13019     22000 Invalid property modify mode.(%s)
     13020     22000 Invalid GOLDILOCKS_DATA directory
     13021     22000 Invalid SID
     13022     HY004 Invalid property data type
     13023     22000 Invalid property ID
     13024     HY000 exceeded maximum number of processes
     13025     HY000 Property file does not exist (%s)
     13026     HY000 Property file already exists (%s)
     13027     HY000 Property file is corrupted
     13028     HY000 Property is not read-only
     13029     HY000 Read-only property file already exists
     13030     HY000 failed to parse the property file (line : %d)
     13031     0A000 Unsupported return type is used
     13032     0A000 Function does not exist
     13033     HY000 It can not make range
     13034     RD000 Service is not available
     13035     HY000 Specified breakpoint name is not registered yet
     13036     HY000 General abort error of breakpoint
     13037     HY000 Invalid session name
     13038     HYT00 Exceeded maximum idle time
     13039     HYT00 Exceeded maximum query time
     13040     08S01 Communication link failure
     13041     RD000 User session ID does not exist
     13042     08004 Server rejected the connection
     13043     HY008 operation canceled
     13044     RD000 invalid process identifier
     13045     08004 mismatched binary version - server(%s.%d.%d.%d.%d), client(%s.%d.%d.%d.%d)
     13046     HY000 session cannot be killed now
     13047     22003 data is outside the range of the data type to which the number is being converted
     13048     22015 one or more fields of data value were truncated during conversion
     13049     HYC00 not implemented feature, in a function %s
     13050     HY000 insufficient plan cache memory
     13051     HY000 Unable to attach the shared memory segment. File does not exist(%s)
     13052     42000 invalid dump option string: %s
     13053     42000 dump object modified by concurrent statement
     13054     42000 invalid numa map (%s)
     13055     HY000 AS ADMIN must be executed in dedicated session
     13056     HY000 unable to create file '%s' - already in use
     13057     HY000 Property(%s) is deprecated
     13058     HY000 memory alloc size is too large: [MAX: %ld, ALLOC: %ld] DESC: (%d)%s
     13059     HYT00 Exceeded maximum packet allocation time
     14000     HY000 Failed to initialize storage manager layer
     14001     HY000 storage manager layer is not initialized yet
     14002     HY000 Tablespace(%d) exceed datafile limit
     14003     HY000 Tablespace(%d) is full
     14004     HY000 Tablespace(%d) is already dropped
     14005     HY000 System tablespace is exists
     14006     42000 Table is mutating, trigger/function may not see it
     14007     RD000 deadlock detected
     14008     24000 fetch out of sequence
     14009     2200H sequence generator limit exceeded
     14010     22023 MAXVALUE cannot be made to be less than the current value
     14011     22023 MINVALUE cannot be made to exceed the current value
     14012     22023 cannot be made to be less than the current value
     14013     22023 cannot be made to exceed the current value
     14014     HY000 failed to extend datafile(%u) of tablespace(%u) in transaction(%ld)
     14015     HY000 there is no extendible datafile in tablespace '%s'
     14016     23001 some rows of base table violate uniqueness of index
     14017     42000 invalid operation on fixed table or dump table
     14018     42000 the operation is disallowed before %s startup phase
     14019     HY000 log stream number string is invalid
     14020     HY000 log stream %d already exists
     14021     HY000 log group number string is invalid
     14022     HY000 log group(%d) state must be INACTIVE or UNUSED
     14023     HY000 log group %d already exists
     14024     HY000 log member %s already exists
     14025     42000 invalid dump option string: %s
     14026     HYT00 resource busy or timeout expired
     14027     HY000 datafile(%d,%d) is already dropped
     14028     HY000 file '%s' is already exist
     14029     HY000 sequence is not yet defined
     14030     RD000 maximum index depth(%d) exceeded
     14031     HY000 maximum key length(%d) exceeds
     14032     40001 transaction rollback: can't serialize access for this transaction
     14033     42000 unable to checkpoint in cds mode
     14034     42000 unable to recover database in cds mode
     14035     42000 some rows of base table violate not null constraint
     14036     42000 invalid ROWID
     14037     42000 Database is READ ONLY
     14038     42000 unable to recover database in READ ONLY mode
     14039     HY000 exceed segment MAXSIZE(%ld)
     14040     HY000 Target object of dump table is mutating
     14041     42000 cannot access the OFFLINE tablespace '%s' 
     14042     42000 cannot find the row (%ld)
     14043     42000 file is already used in database '%s'
     14044     42000 datafile not empty
     14045     42000 cannot drop datafile of OFFLINE tablespace '%s'
     14046     42000 file does not exist - '%s'
     14047     42000 file is READ ONLY - '%s'
     14048     42000 file is invalid or old version - '%s'
     14049     42000 tablespace is not online - '%s'
     14050     42000 tablespace is not offline - '%s'
     14051     42000 media recovery required - '%s'
     14052     42000 segment is unusable ( physical id : %ld )
     14053     RD000 insufficient resource for sort
     14054     HY000 internal error ( %s, %d )
     14055     HY000 segment is corrupted ( physical id : %ld )
     14056     HY000 failed to apply redo log ( lsn : %ld, lpsn : %d, physical id : %ld )
     14057     HY000 dropping log group makes total log group count less than minimum log group count(%d)
     14058     42000 log member is not exist - '%s'
     14059     42000 log member is already used - '%s'
     14060     HY000 CURRENT logfile is empty - '%s'
     14061     HY000 next logfile to switch should be INACTIVE or UNUSED - '%s'
     14062     42000 INITRANS must be less equal than MAXTRANS
     14063     42000 cannot be added log member to exceed maximum log member count(%d)
     14064     42000 the operation is disallowed at %s phase
     14065     RD000 the instant table row length is too large
     14066     RD000 the sort instant table key row length is too large
     14067     HY000 cannot media recover; archivelog mode not enabled - deprecated
     14068     HY000 logfile does not exist - '%s'
     14069     HY000 cannot support ARCHIVELOG in cds mode
     14070     HY000 control file is not recent; do media recovery
     14071     HY000 cannot backup; tablespace(%s) is offline
     14072     HY000 cannot backup; tablespace(%s) is temporary
     14073     HY000 cannot backup; tablespace is dropped
     14074     HY000 cannot backup; tablespace(%s) is already in backup
     14075     HY000 cannot execute; tablespace(%s) is proceeding backup
     14076     HY000 cannot end backup; tablespace(%s) is not in backup
     14077     HY000 cannot end backup; none of the tablespaces are in backup
     14078     HY000 cannot backup; tablespace(%s) is proceeding other operation
     14079     HY000 cannot backup; database is already in backup
     14080     HY000 cannot end backup; database is not in backup
     14081     HY000 cannot backup; database is going shutdown
     14082     HY000 (%s) is not an appropriate logfile to recover
     14083     HY000 must use RESETLOGS option for database open
     14084     HY000 must use NORESETLOGS option for database open
     14085     HY000 checkpoint lsn(%ld) of '%s' was not a sufficiently old - older backup than last recovered lsn(%ld) is required
     14086     HY000 media recovery canceled
     14087     HY000 cannot shutdown; backup in progress
     14088     HY000 control file is corrupted
     14089     HY000 level 0 incremental backup does not exist
     14090     HY000 cannot flush logs; disabled log flushing
     14091     HY000 (%s) is not valid logfile
     14092     HY000 not exist incremental backup
     14093     HY000 not exist valid incremental backup for tablespace(%s)
     14094     HY000 datafile recovery required - datafile(%s) of tablespace(%s) corrupted
     14095     HY000 backup file(%s) is corrupted
     14096     23001 fail to build index ( %ld )
     14097     HY000 control file is corrupted - '%s'
     14098     HY000 maximum record length(%ld) exceeds
     14099     HY000 log member state must be UNUSED or INACTIVE
     14100     HY000 dropping log member makes log member count of group(%d) less than minimum log member count(%d)
     14101     HY000 log group id does not exist - '%d'
     14102     HY000 cannot execute; recovery is in progress
     14103     01000 Warning: media recovery needs a logfile including log (Lsn %ld)
     14104     01000 Warning: suggestion '%s'
     14105     HY000 control file '%s' is inconsistent with primary
     14106     HY000 tablespace (%s) is taken offline as the result of a write error
     14107     HY000 given LOG_BLOCK_SIZE(%ld) is not a suitable value for a size of log block; LOG_BLOCK_SIZE should be one of 512, 1024, 2048 or 4096.
     14108     HY000 cannot disable archivelog - exist tablespace needed media recovery.
     14109     HY000 OFFLINE NORMAL disallowed; cannot be taken offline consistently.
     14110     HY000 OFFLINE IMMEDIATE disallowed; noarchivelog mode
     14111     HY000 cannot create table with columnar option; given MIN ROW COUNT is too big to put into one page
     14112     HY000 record size is too large for columnar table
     14113     HY000 datafile '%s' is corrupted
     14114     HY000 exist inconsistent datafiles; need to restore more older backup datafiles or more recent redo logfiles
     14115     HY000 transaction undo limit exceeded
     14116     HY000 failed to journal log
     14117     HY000 cannot end incomplete recovery; incomplete recovery never been begun
     14118     HY000 property TRANSACTION_TABLE_SIZE value must be equal to or greater than '%d'
     14119     HY000 property UNDO_RELATION_COUNT value must be equal to or greater than '%ld'
     14120     HY000 sequence is dropped
     14121     HY000 file '%s' does not match with database - file signature '%s', database signature '%s'
     14122     HY000 there is a possibility that a deadlock occurs
     14123     22023 INCREMENTBY sign cannot be changed in the cluster system
     14124     HY000 RESTORE in progress
     14125     HY000 exceed maximum journal file size
     14126     HY000 there must be at least one irrecoverable member in the group
     14127     HY000 object no longer exists
     14128     HY000 invalid remote view scn
     14129     HYT00 transaction allocation time exceeded
     14130     HYT00 undo relation allocation time exceeded
     14131     42000 unable to enable change tracking in cds mode
     14132     42000 unable to enable change tracking in noarchivelog mode
     14133     HY000 change tracking is already enabled
     14134     HY000 change tracking is not enabled
     14135     HY000 change tracking file is corrupted - '%s'
     14136     HY000 failed to backup incremental because change tracking is being altered
     14137     HY000 failed to disable change tracking because incremental backup is in progress
     14138     HY000 exceed maximum insertable records ( %lu ) by transaction
     14139     HY000 transaction(%ld) is timed out for waiting to resolve cluster deadlock
     15000     HY000 failed to initialize execution library layer
     15001     HY000 execution library layer is not initialized yet
     15002     42000 "%s": schema does not exist
     15003     42000 "%s": table or view does not exist
     15004     42000 "%s": index does not exist
     15005     42000 "%s": column does not exist
     15006     23000 "%s": dictionary integrity constraint violation by concurrent DDL execution
     15007     HY090 not enough stack space to add entries
     15008     HY000 table related objects are modified while validation
     15009     HY000 Invalid argument
     15010     42000 object modified by concurrent DDL execution
     15011     HYC00 not implemented feature, in a function %s
     15012     42000 user dropped by other session
     15013     42000 user default schema dropped
     15014     42000 user default data tablespace dropped
     15015     42000 user default temporary tablespace dropped
     15016     0Y002 limit(%d) on the number of named cursor exceeded
     15017     42000 DDL not allowed for supplemental log table
     15018     42000 cluster member '%s' has already joined in an other cluster system
     15019     42000 the %s of cluster member '%s' is not compatible with the cluster system
     15020     42000 tablespace '%s' of the cluster system does not exist at cluster member '%s'
     15021     42000 tablespace '%s' of the cluster member '%s' does not exist at the cluster system
     15022     42000 the %s of the tablespace '%s' at cluster member '%s' is not compatible with the cluster system
     15023     HY000 limit(%d) on the number of named instant table exceeded
     15024     42000 the cluster member '%s' does not join in a cluster system
     15025     42000 startup phase of new cluster member should be OPEN
     15026     HY000 internal error, in a function %s
     15027     42000 attempt to create, alter or drop an index on temporary table already in use
     15028     42000 user default index tablespace dropped
     16000     HY000 failed to initialize sql processor layer
     16001     HYC00 not implemented feature, in a function %s
     16002     HY000 invalid function sequence of sql processor layer
     16003     42000 identifier is too long
     16004     28000 invalid username/password; logon denied
     16005     42000 name '%s.%s' is already used by an existing object
     16006     42000 schema '%s' does not exist
     16007     42000 schema '%s' is not writable
     16008     42000 tablespace '%s' does not exist
     16009     42000 tablespace '%s' is not writable
     16010     42000 invalid value for PCTFREE or PCTUSED
     16011     42000 invalid INITRANS option value
     16012     42000 duplicate column name
     16013     HY000 invalid value is prevented in validation step
     16014     22023 INCREMENT must be a non-zero integer
     16015     22023 START WITH cannot be less than MINVALUE
     16016     22023 START WITH cannot be more than MAXVALUE
     16017     22023 the number of values to CACHE must be greater than 1
     16018     22023 number to CACHE must be less than one cycle
     16019     22023 MINVALUE must be less than MAXVALUE
     16020     22023 INCREMENT must be less than MAXVALUE minus MINVALUE
     16021     22023 descending sequences that CYCLE must specify MINVALUE
     16022     22023 ascending sequences that CYCLE must specify MAXVALUE
     16023     22023 duplicate or conflicting CACHE/NO CACHE specifications
     16024     42000 numeric precision specifier is out of range( %d to %d )
     16025     42000 numeric scale specifier is out of range( %d to %d )
     16026     42000 character length specifier is out of range( 1 to %d )
     16027     42000 character varying length specifier is out of range( 1 to %d )
     16028     42000 binary length specifier is out of range( 1 to %d )
     16029     42000 binary varying length specifier is out of range( 1 to %d )
     16030     42000 name already used by an existing constraint
     16031     42000 auto-generated name already used by an existing constraint, specify unique constraint name
     16032     42000 table can have only one primary key
     16033     42000 such unique or primary key already exists in the table
     16034     42000 name already used by an existing index
     16035     42000 auto-generated name already used by an existing index, specify non-duplicate index name
     16036     42000 '%s': invalid identifier
     16037     42000 maximum number of key columns exceeded
     16038     23000 integrity constraint violation
     16039     3B000 savepoint '%s' never established in this session or is invalid
     16040     42000 table or view does not exist
     16041     42000 table '%s' is not writable
     16042     42000 unique/primary keys in table referenced by foreign keys
     16043     42000 table referenced by views
     16044     42000 sequence does not exist
     16045     42000 duplicate options
     16046     42000 such column list already indexed
     16047     22003 numeric value out of range
     16048     42000 specified index does not exist
     16049     42000 index '%s' is not writable
     16050     42000 cannot modify index used for enforcement of unique/primary/foreign key
     16051     HY000 not applicable
     16052     42000 column not allowed here
     16053     42000 not enough values
     16054     42000 too many values
     16055     22004 NULL value not allowed
     16056     22004 cannot insert NULL into "%s"."%s"."%s"
     16057     23000 unique constraint (%s.%s) violated
     16058     42000 not applicable hint ( %s )
     16059     42000 not applicable datatype
     16060     07002 bind variable does not exist
     16061     22004 cannot update ("%s"."%s"."%s") to NULL
     16062     42000 syntax error
     16063     42000 fractional seconds precision specifier is out of range( %d to %d )
     16064     42000 invalid interval indicator
     16065     42000 interval leading precision specifier is out of range( %d to %d )
     16066     42000 interval fractional seconds precision specifier is out of range( %d to %d )
     16067     42000 invalid INITIAL storage option value
     16068     42000 invalid NEXT storage option value
     16069     42000 invalid MINSIZE storage option value
     16070     42000 invalid MAXSIZE storage option value
     16071     42000 storage option MAXSIZE is less than MINSIZE
     16072     42000 duplicate or conflicting NULL and/or NOT NULL specifications
     16073     42000 duplicate UNIQUE/PRIMARY KEY specifications
     16074     42000 sequence number not allowed here
     16075     42000 inconsistent datatypes : expected %s
     16076     42000 invalid DATAFILE clause for alter of %s %s TABLESPACE
     16077     42000 invalid DATAFILE clause for alter of %s %s TABLESPACE
     16078     42000 invalid TEMPFILE clause for alter of %s %s TABLESPACE
     16079     42000 file path is too long ( < %d )
     16080     RD000 file size is out of range( %ld to %ld )
     16081     42000 failed to open database : system threads are already exist.
     16082     42000 invalid MAXTRANS option value
     16083     42000 INITRANS must be less equal than MAXTRANS
     16084     42000 result OFFSET must be 0 or positive numeric value
     16085     42000 result LIMIT/FETCH must be positive numeric value
     16086     42000 related objects are modified by concurrent DDL execution
     16087     42000 boolean expression expected on where clause
     16088     HY000 session cannot be killed now
     16089     28000 built-in authorization(user or role) '%s' is not modifiable
     16090     42000 built-in tablespace '%s' is not modifiable
     16091     42000 built-in schema '%s' is not modifiable
     16092     42000 built-in table or view '%s' is not modifiable
     16093     42000 built-in index '%s' is not modifiable
     16094     42000 built-in constraint '%s' is not modifiable
     16095     42000 built-in sequence '%s' is not modifiable
     16096     28000 authorization(user or role) '%s' does not exist
     16097     42000 constraint '%s' does not exist
     16098     07006 bind type mismatch of parameter number (%d)
     16099     42000 the number of elements in the INTO list is mismatch
     16100     HY000 single-row subquery returns more than one row
     16101     42000 parallel factor is out of range( 0 to %d )
     16102     42000 invalid MEMORY clause for alter of %s %s TABLESPACE
     16103     3C000 cursor '%s' is already declared
     16104     42000 invalid cursor query: '%s'
     16105     42000 invalid cursor property
     16106     34000 cursor '%s' does not exist
     16107     34000 cursor '%s' is already open
     16108     34000 cursor '%s' is not open
     16109     42000 invalid use: cursor '%s' is not a declared cursor
     16110     42000 invalid use: cursor '%s' is not an ODBC/JDBC cursor
     16111     42000 cursor '%s' is not scrollable
     16112     42000 query expression is not updatable
     16113     42000 invalid phase(%s): executable phase of '%s' is between %s and %s
     16114     42000 database is already mounted
     16115     42000 database is already local opened
     16116     42000 transaction is READ ONLY
     16117     42000 database is not mounted
     16118     42000 supplemental logging attribute primary key exists
     16119     42000 cannot drop nonexistent primary key supplemental logging
     16120     42000 column referenced by views
     16121     42000 column has a check constraint defined
     16122     42000 pseudo column not allowed here
     16123     42000 cannot select %s from not writable table
     16124     42000 table can have only one identity column
     16125     42000 column being added already exists in table
     16126     42000 table must be empty to add mandatory (%s) column ('%s')
     16127     42000 cannot modify INITIAL storage option
     16128     42000 name '%s' is already used by an existing tablespace
     16129     42000 duplicate datafile name
     16130     42000 file is already exist - '%s'
     16131     42000 cannot rename the built-in tablespace
     16132     42000 cannot rename the OFFLINE tablespace
     16133     42000 cannot drop the built-in tablespace
     16134     42000 cannot drop constraint - nonexistent constraint
     16135     42000 cannot drop constraint - nonexistent primary key
     16136     42000 cannot drop constraint - nonexistent unique key
     16137     42000 the CDS database cannot be closed with ABORT option
     16138     42000 the DS database can be closed with NORMAL option - deprecated
     16139     42000 multiple ORDER BY clauses not allowed
     16140     42000 multiple OFFSET clauses not allowed
     16141     42000 multiple LIMIT clauses not allowed
     16142     42000 column ambiguously defined
     16143     42000 column part of USING clause cannot have qualifier
     16144     42000 invalid OFFSET option value
     16145     42000 invalid LIMIT option value
     16146     42000 common column name '%s' appears more than once in %s table
     16147     42000 file is already used in database
     16148     42000 tablespace not empty, use INCLUDING CONTENTS option
     16149     42000 datafile does not exist in tablespace
     16150     42000 cannot drop datafile of OFFLINE tablespace
     16151     42000 cannot drop first datafile of tablespace
     16152     42000 memory is already used in database
     16153     42000 memory does not exist in tablespace
     16154     42000 cannot drop first memory of tablespace
     16155     42000 tablespace '%s' is not writable for logging index
     16156     42000 tablespace '%s' is not writable for nologging index
     16157     42000 ORDER BY item must be the number of a SELECT-list expression
     16158     42000 group function is not allowed here
     16159     42000 invalid number of arguments
     16160     42000 group function is nested too deeply
     16161     42000 not a single-group group function
     16162     42000 mismatched datafile pairs
     16163     42000 cannot rename datafile of ONLINE tablespace
     16164     42000 file does not exist
     16165     42000 tablespace is not online
     16166     42000 tablespace is not offline
     16167     42000 cannot offline temporary tablespace
     16168     42000 cannot offline dictionary tablespace
     16169     42000 cannot offline undo tablespace
     16170     42000 invalid WAIT interval
     16171     42000 column is not updatable
     16172     22003 data is outside the range of the data type to which the number is being converted
     16173     22015 one or more fields of data value were truncated during conversion
     16174     42000 system session cannot be killed
     16175     42000 hint not allowed in positioned DELETE
     16176     42000 hint not allowed in positioned UPDATE
     16177     34000 cursor '%s' is not updatable
     16178     34000 cursor cannot identify the underlying table
     16179     HY109 cursor was not positioned on a certain row
     16180     HY109 cursor was positioned on a row that had been deleted
     16181     42000 the CDS database cannot be closed with OPERATIONAL option
     16182     42000 invalid segment identifier
     16183     42000 FETCH position must be numeric value
     16184     42000 cannot drop all columns in a table
     16185     42000 column already has a NOT NULL constraint
     16186     42000 column does not have a NOT NULL constraint
     16187     42000 null values found
     16188     HY000 result set does not exist
     16189     42000 column is not an identity column
     16190     42000 column cannot be cast to incompatible type
     16191     42000 column cannot be cast to decrease precision or scale
     16192     42000 column cannot be cast to decrease string length
     16193     42000 column cannot be cast to incompatible char length unit
     16194     42000 column cannot be cast to incompatible interval indicator
     16195     42000 float precision specifier is out of range( %d to %d )
     16196     42000 file is already used in log stream - '%s'
     16197     42000 duplicate logfile name
     16198     42000 size of log file is smaller than minimum size of log file(%ld bytes).
     16199     42000 can not find specified log member.
     16200     42000 the number of source logfiles is different from the number of targets
     16201     42000 can not find specified log file.
     16202     42000 name '%s' is already used by an existing schema
     16203     42000 schema not empty, use CASCADE option
     16204     RD000 another checkpoint is in progress
     16205     42000 boolean expression expected
     16206     RD000 maximum number of arguments exceeded
     16207     42000 %s and %s cannot be matched
     16208     42000 insufficient privileges
     16209     42000 user %s lacks CREATE SESSION privilege; logon denied
     16210     42000 lacks privilege (%s ON DATABASE)
     16211     42000 lacks privilege (%s ON TABLESPACE "%s")
     16212     42000 lacks privilege (%s ON SCHEMA "%s")
     16213     42000 user name '%s' conflicts with another user or role name
     16214     42000 tablespace '%s' is not data tablespace
     16215     42000 tablespace '%s' is not temporary tablespace
     16216     28000 user '%s' does not exist
     16217     42000 user has own schema: DROP SCHEMA first
     16218     42000 CASCADE must be specified to drop user '%s'
     16219     42000 you may not GRANT/REVOKE privileges to/from yourself
     16220     42000 duplicate authorization name in grantee/revokee list
     16221     42000 user default schema dropped
     16222     42000 user default data tablespace dropped
     16223     42000 user default temporary tablespace dropped
     16224     42000 no privileges to GRANT ALL PRIVILEGES
     16225     42000 insufficient privilege to GRANT
     16226     42000 duplicate privilege listed
     16227     42000 cannot drop a user that is currently connected
     16228     42000 fixed table not grantable/revokable
     16229     42000 invalid old password
     16230     42000 schema element does not match schema identifier
     16231     28000 cannot GRANT/REVOKE privileges to/from built-in authorization
     16232     28000 cannot REVOKE privileges you did not grant to '%s'
     16233     HY000 OFFLINE IMMEDIATE disallowed; noarchivelog mode
     16234     HY000 OFFLINE IMMEDIATE disallowed; no logging tablespace
     16235     2B000 dependent privilege descriptors still exist
     16236     0A000 not supported query%s
     16237     42000 a subquery block has incorrect number of result columns
     16238     42000 ORDER BY item must be the number of a SELECT-list expression
     16239     42000 expression must have same datatype as corresponding expression
     16240     42000 subquery expressions not allowed here
     16241     42000 invalid number of column names specified
     16242     42000 must name this expression with a column alias
     16243     01000 Warning: View definition has compilation errors
     16244     42000 bind variables not allowed for data definition operations
     16245     42000 view "%s.%s" has errors
     16246     42000 illegal use of %s data type
     16247     HY000 cannot BACKUP; noarchivelog mode
     16248     HY000 cannot RECOVER TABLESPACE; tablespace is in use
     16249     HY000 cannot SHUTDOWN; backup in progress
     16250     HY000 RECOVER UNTIL CANCEL can be issued by directly attached session only - deprecated
     16251     42000 single-row subquery returns more than one row
     16252     42000 circular view definition encountered
     16253     42000 only base table columns are allowed to GRANT/REVOKE
     16254     42000 lacks privilege (%s ON TABLE "%s"."%s")
     16255     42000 lacks privilege (USAGE ON SEQUENCE "%s"."%s")
     16256     07001 wrong number of parameters
     16257     HY000 argument of CASE/WHEN must be type boolean
     16258     HY000 the XID does not exist
     16259     HY000 the XID string is not valid
     16260     HY000 the global transaction is in progress
     16261     42000 invalid INCREMENTAL BACKUP LEVEL specified : %ld
     16262     42000 INCREMENTAL BACKUP LEVEL 0 cannot have any BACKUP options
     16263     HY000 cannot RESTORE TABLESPACE; tablespace is in use
     16264     HY000 transaction is in progress
     16265     42000 outer join operator (+) cannot be used with ANSI joins
     16266     42000 outer join operator (+) not allowed in %s
     16267     42000 an outer join cannot be specified on a correlation column
     16268     42000 a predicate may reference only one outer-joined table
     16269     42000 a table may be outer joined to at most one other table
     16270     42000 two tables cannot be outer-joined to each other
     16271     42000 RESTART value cannot be made to be less than the MINVALUE
     16272     42000 RESTART value cannot be made to exceed the MAXVALUE
     16273     42000 MINVALUE cannot be made to exceed the current value
     16274     42000 MAXVALUE cannot be made to be less than the current value
     16275     42000 MINVALUE cannot be made to exceed the START WITH value
     16276     42000 MAXVALUE cannot be made to be less than START WITH value
     16277     42000 log group id is already used
     16278     42000 identity column cannot have a default value
     16279     42000 DEFAULT expression has errors
     16280     42000 the statement is disallowed
     16281     42000 resource manager doing work outside transaction
     16282     42000 MEMORY tablespace does not support an AUTOEXTEND option
     16283     HY000 invalid ROWID
     16284     42000 unable to execute in CDS mode
     16285     RP000 failed to create system threads (%s)
     16286     HY000 valid incremental backup does not exist
     16287     42000 log group id does not exist
     16288     42000 invalid string value specified
     16289     42000 into clause can have only one row
     16290     42000 SHUTDOWN must be executed in dedicated session
     16291     40002 transaction rollback: integrity constraint violation
     16292     42000 column length specifier is out of range( 1 to %d ) for columnar table
     16293     42000 columnar table does not support LONGVARCHAR and LONGVARBINARY
     16294     42000 cannot defer a constraint that is not deferrable
     16295     42000 invalid NOT NULL constraint specified on an identity column
     16296     42000 constraint '%s' is not deferrable
     16297     42000 duplicate constraint name specified
     16298     42000 cannot make primary key supplemental log data with primary key constraint violation
     16299     42000 datafile does not exist in database
     16300     42000 too many SQL resource
     16301     42000 name '%s' is already used by an existing public synonym
     16302     42000 private synonym '%s' to be droppped does not exist
     16303     42000 public synonym '%s' to be droppped does not exist
     16304     42000 looping chain of synonyms
     16305     42000 synonym translation is no longer valid
     16306     42000 expression is out of iteration time scope
     16307     42000 constant value expression expected
     16308     42000 invalid or redundant resource
     16309     28000 the account is locked
     16310     28000 the password will expire in %ld days
     16311     28000 the password will expire soon
     16312     28000 the password has expired
     16313     28000 the password cannot be reused
     16314     42000 cannot lock "SYS" account
     16315     42000 profile '%s' already exists
     16316     42000 function '%s' not found
     16317     42000 profile '%s' has users assigned, cannot drop without CASCADE
     16318     42000 profile '%s' does not exist
     16319     42000 cannot assign PROFILE to "SYS" account
     16320     42000 cannot assign DEFAULT parameter value to "DEFAULT" profile
     16321     42000 password length less than '%ld'
     16322     42000 password must contain at least '%ld' letter(s)
     16323     42000 password must contain at least uppercase '%ld' character(s)
     16324     42000 password must contain at least lowercase '%ld' character(s)
     16325     42000 password must contain at least '%ld' digit(s)
     16326     42000 password must contain at least '%ld' special character(s)
     16327     42000 password same as or similar to user name
     16328     42000 password contains the user name reversed
     16329     42000 password same as or similar to database name
     16330     42000 password too simple
     16331     42000 Password should differ from the old password by at least '%d' characters
     16332     42000 constant value does not support LONGVARCHAR and LONGVARBINARY
     16333     42000 value of parameter number (%d) must be consistent datatype
     16334     42000 invalid value is prevented in parameter number (%d)
     16335     42000 UPDATE primary key not allowed for supplemental log table
     16336     42000 cluster group '%s' does not exist
     16337     42000 duplicate cluster object listed
     16338     42000 cluster domain '%s' does not exist
     16339     42000 invalid hash shard count (must between %d and %d)
     16340     42000 not found available sharding key column
     16341     42000 cannot specifiy sharding strategy and placement for a table on dictionary schema '%s' 
     16342     HYC00 not implemented feature for cluster system, in a function %s 
     16343     42000 invalid syntax for a stand-alone system
     16344     42000 database is not local opened
     16345     42000 database is already opened
     16346     42000 name '%s' is already used by an existing cluster object
     16347     42000 cluster port is out of range( %d to %d )
     16348     42000 duplicate cluster connection listed
     16349     42000 the first cluster group does not contain local cluster member '%s'
     16350     42000 maximum number of cluster members exceeded
     16351     08000 failed to connect to the cluster member '%s'
     16352     42000 mismatch local cluster member with location file
     16353     42000 conflict between new cluster member and location file
     16354     HY000 connection of member '%s' is broken
     16355     42000 non-deterministic function not allowed here
     16356     42000 version conflict
     16357     42000 must be accessible to at least one member of group '%s'
     16358     42000 accessable member does not exist
     16359     42000 no inactive members
     16360     42000 cloned table "%s"."%s" must be accessible to at least one member
     16361     42000 sharded table "%s"."%s" must be accessible to at least one member of group '%s'
     16362     42000 NODE SHARDED table cannot be rebalanced
     16363     42000 the cluster member '%s' failed to join the cluster system
     16364     42000 cluster group has sharded data
     16365     42000 schema name of instant table must be SESSION_SCHEMA
     16366     42000 hash shard count smaller than AT CLUSTER GROUP list
     16367     42000 cannot drop sharding key column
     16368     42000 not a fixed table
     16369     42000 not a statistics table
     16370     42000 have to create one or more datafiles to each member
     16371     42000 conversion is not applicable
     16372     42000 duplicate shard name
     16373     42000 the number of elements in shard bound mismatch the sharding key columns
     16374     42000 range shard bound value must be one of: valid constant or MAXVALUE
     16375     42000 only MAXVALUE allowed after MAXVALUE
     16376     42000 multiple MAX shard defined
     16377     42000 MAX shard not defined
     16378     42000 duplicate shard bound value
     16379     42000 of the total '%d' tables, '%d' tables failed to rebalance
     16380     HYC00 UNIQUE or PRIMARY KEY must include all sharding key columns for cluster system
     16381     42000 invalid shard count (must between %d and %d)
     16382     42000 cluster member '%s' does not exist
     16383     42000 domain '%s' is unknown
     16384     42000 multiple DEFAULT shard defined
     16385     42000 DEFAULT shard not defined
     16386     42000 DEFAULT cannot be specified with other values
     16387     42000 list shard bound value must be one of: valid constant or NULL or DEFAULT
     16388     HYC00 does not support deferrable constraints in the cluster system
     16389     42000 domain names of the datafile for renaming don't mismatch
     16390     42000 invalid table for sharding strategy and placement specified
     16391     42000 the number of sharding key in function is mismatch
     16392     HYC00 does not support ROWID in the cluster system
     16393     01000 Warning: accessable member does not exist
     16394     01000 Warning: connection of member '%s' is broken
     16395     01000 Warning: must be accessible to at least one member of group '%s'
     16396     42000 exceeds the maximum number of nodes
     16397     42000 exceeds the maximum number of groups
     16398     42000 the domain of property does not match with domain '%s'
     16399     42000 cannot insert or update a generated always identity column, value shall be a DEFAULT
     16400     HY000 cannot RECOVER UNTIL CHANGE SCN; invalid SCN format
     16401     42000 invalid SAMPLE size specified
     16402     42000 duplicate index name
     16403     42000 of the total '%d' nodes, '%d' nodes failed to join the global database
     16404     42000 cannot execute the statement with OS user permissions
     16405     42000 of the total '%d' tables in the database, '%d' tables need to be rebalanced
     16406     42000 invalid routine name
     16407     42000 procedure or function does not exist
     16408     42000 bind variables not allowed for procedures or functions
     16409     01000 Warning: Routine definition has compilation errors
     16410     42000 Startup driver node must have the latest data - a suitable startup driver node is '%s' member
     16411     42000 maximum number of recursive SQL levels (%d) exceeded.
     16412     42000 all of shards in a table '%s' must be online.
     16413     42000 LOCAL_OFFLINE domain must be specified to base table
     16414     42000 domain option not allowed here
     16415     42000 LOCAL_OFFLINE domain cannot be used with other domains
     16416     42000 lacks privilege (EXECUTE ON PROCEDURE "%s"."%s")
     16417     42000 active member '%s' cannot be offlined
     16418     42000 cluster member '%s' does not exist in cluster group '%s'
     16419     42000 object identifier not allowed here
     16420     0A000 does not support adding identity column in the cluster system
     16421     0A000 does not support deferred unqiue integrity in the cluster system
     16422     0A000 does not support SERIALIZABLE in the cluster system
     16423     42000 does not support non-deterministic DML in the cluster system : global secondary index expected
     16424     42000 function generating different values is not allowed here
     16425     42000 procedure, function, package, or type is not allowed here
     16426     42000 does not support ADD COLUMN DEFAULT generating different values in the cluster system
     16427     42000 invalid events (%s)
     16428     42000 cluster system is modified by concurrent cluster DDL execution
     16429     42000 does not support cursor in the cluster system : global secondary index expected
     16430     42000 the cluster database can be closed only with ABORT or NORMAL option
     16431     42000 non-deterministic expression not allowed here : may lead to a replica synchronization failure
     16432     42000 global secondary index already exists in table
     16433     42000 global secondary index does not exist in table
     16434     HY000 invalid grid is prevented in cluster operation, in a function %s
     16435     HY000 duplicate source datafile name
     16436     HY000 duplicate target datafile name
     16437     42000 cannot execute on cloned tables
     16438     42000 invalid shard name
     16439     42000 cannot move shard to the same group
     16440     42000 cannot execute on cluster wide sharded tables
     16441     42000 not analyzed table
     16442     42000 invalid analyzed file format (%s)
     16443     42000 old plan
     16444     42000 invalid cluster group name
     16445     42000 REBALANCE EXCLUDE can be executed only on cluster wide sharded tables
     16446     42000 REBALANCE EXCLUDE target group is empty
     16447     HY000 internal error ( %s, %d )
     16448     42000 of the total '%d' tables, '%d' tables failed to move shard
     16449     42000 cluster group does not have sharded data
     16450     42000 exceeded global property lock timeout
     16451     42000 rownum not allowed here
     16452     42000 rownum not allowed in sensitive cursor
     16453     42000 rownum not allowed in positioned UPDATE
     16454     42000 function '%s' not allowed here
     16455     42000 routine "%s.%s" has errors
     16456     42000 the startup phase '%s' of cluster member '%s' is mismatch with the required startup phase '%s'
     16457     42000 the connection map of cluster member '%s' is mismatch with local connection map
     16458     42000 reserved domain cannot be used with other domains
     16459     42000 cannot execute on hash sharded tables
     16460     42000 cannot execute on range sharded tables
     16461     42000 invalid shard values
     16462     42000 cannot split shard - source shard cannot be empty
     16463     42000 first CREATE CLUSTER GROUP must include only one cluster member
     16464     HY000 unsupported feature with temporary table
     16465     42000 cannot drop local cluster group
     16466     42000 cannot execute with SERIALIZABLE
     16467     42000 table '%s' is READ ONLY
     16468     HY000 cannot create TEMPORARY object in a NON-TEMPORARY tablespace
     16469     42000 cannot execute on global connection
     16470     42000 datafile size specified is smaller than minimum required '%ld'
     16471     42000 audit policy '%s' does not exists
     16472     42000 audit policy cannot be dropped as it is currently enabled
     16473     42000 audit policy '%s' already exists
     16474     42000 not auditable option
     16475     42000 audit policy already applied with the BY clause
     16476     42000 audit policy already applied with the EXCEPT clause
     16477     42000 not auditable object
     16478     42000 tablespace '%s' is not temporary tablespace or data tablespace
     16479     42000 failed to update system version - %s
     16480     42000 cannot set irrecoverable on the local cluster member
     16481     42000 global tempoary table segment no longer exists
     16482     42000 database is not accessible; '%s' has detached from the cluster
     16483     42000 of the total '%d' sequences, '%d' sequences failed to synchronize
     16484     42000 of the total '%d' identity columns, '%d' identity columns failed to synchronize
     16485     42000 table does not have an identity column
     16486     RD000 maximum file size is out of range( %ld to %ld )
     16487     42000 only range sharded table is allowed
     16488     42000 shards being merged are not adjacent
     16489     42000 cluster group name must be specified
     16490     42000 mismatch the group name of the source shard '%s'
     16491     42000 exceed the maximum number of shards (%d)
     16492     42000 can not perform DDL/DML over objects in Recycle Bin
     16493     42000 object not in Recycle Bin
     16494     42000 original name is used by an existing object
     16495     HY000 package or package body does not exist
     16496     42000 built-in package '%s' is not modifiable
     16497     42000 lacks privilege (EXECUTE ON PACKAGE "%s"."%s")
     16498     42000 Only Btree indexes can be rebuilt
     16499     42000 operation is not allowed on immutable table '%s'
     16500     42000 cannot execute on global session
     16501     42000 size of log file is larger than maximum size of log file(%ld bytes).
     16502     42000 recursive WITH clause must reference itself directly in one of the UNION ALL branches
     16503     42000 recursive WITH clause must reference itself in the last UNION ALL branch
     16504     42000 recursive WITH clause must use UNION ALL operation
     16505     42000 recursive WITH clause must have column alias list
     16506     42000 unsupported join in recursive WITH query
     16507     42000 cycle mark value and non-cycle mark value must be one byte character
     16508     42000 only recursive WITH element can have recursive search clause
     16509     42000 unsupported operation in recursive branch of recursive WITH clause
     16510     42000 unsupported use of WITH clause
     16511     42000 cycle detected while executing recursive WITH query
     16512     42000 CONNECT BY clause required in this query block
     16513     42000 %s not allowed here
     16514     42000 cycle detected while executing CONNECT BY Clause
     16515     42000 ORDER SIBLINGS BY requires specific target expressions
     16516     42000 invalid argument expressions for SYS_CONNECT_BY_PATH
     16517     42000 NOCYCLE keyword is required with CONNECT_BY_ISCYCLE pseudocolumn
     16518     42000 LOCAL_OFFLINE domain expected
     16519     42000 global secondary index expected in cluster DML
     16520     42000 long varying memory manager does not exist
     16521     42000 invalid hash bucket count (must between 1 and %ld)
     16522     42000 invalid cluster member position
     16523     HY000 the database system is shutting down
     17000     2F000 failed to initialize PSM processor layer
     17001     2F000 not implemented feature (%s)
     17002     2F000 duplicated label name
     17003     2F000 duplicated exception name
     17004     2F000 duplicated variable name
     17005     2F000 not applicable expression type
     17006     2F000 unknown variable or column name (%s)
     17007     2F000 invalid expression
     17008     2F000 wrong number of parameters
     17009     2F000 NOT NULL constraint violation
     17010     2F000 can not find label name
     17011     2F000 duplicated field name
     17012     2F000 unknown type name
     17013     2F000 the type of record field should be scalar
     17014     2F000 target host parameter of assignment is not bound in OUT mode
     17015     2F000 cannot set constraint or initial value on non-scalar-type variable
     17016     2F000 variables which have NOT NULL constraint should have initial values
     17017     2F000 Unhandled user exception
     17018     2F000 Pre-defined-exception name not allowed in declare section
     17019     2F000 OTHERS-exception must be last among the exceptions of a block
     17020     2F000 Unknown exception
     17021     2F000 Invalid error number for PRAGMA EXCEPTION_INIT
     17022     2F000 A CASE statement must either list all possible cases or hava an else clause
     17023     2F000 duplicated error-code in same exception handler
     17024     2F000 (%s) cannot be used as assignment target
     17025     2F000 The command cannot be executed when global transaction is in the ACTIVE state
     17026     2F000 Transaction is READ ONLY
     17027     2F000 duplicated identifier
     17028     2F000 out of scope error
     17029     2F000 too many depths of scope (limit=%d)
     17030     2F000 invalid reference field (%s)
     17031     2F000 mismatch identifier type
     17032     2F000 PSM compilation error
     17033     2F000 duplicated cursor name
     17034     2F000 return type of cursor is invalid
     17035     2F000 invalid expression type
     17036     2F000 cursor is not defined
     17037     2F000 cursor is already open
     17038     2F000 cursor is not open
     17039     2F000 unknown cursor
     17040     2F000 fetch target count mismatch
     17041     2F000 execution fail
     17042     2F000 bind variables not allowed for data definition operations
     17043     2F000 no target-list for into clause
     17044     2F000 returning-into need to bind variable with returning-into or using OUT clause
     17045     2F000 no data found
     17046     2F000 variables of record type can not be mixed with other variables
     17047     2F000 can not use record-type in a expression
     17048     2F000 can not be used with INTO-clause and USING clause having OUT-modes
     17049     2F000 can not use a expression in USING OUT binding
     17050     2F000 query need to bind with INTO-clause for targets
     17051     2F000 invalid statement-type
     17052     2F000 Alias required in list of cursor to avoid duplicated target names
     17053     2F000 schema or table object does not exist
     17054     2F000 only record-type variable allowed
     17055     2F000 this cursor must be declared with FOR-UPDATE to use with CURRENT OF
     17056     2F000 invalid syntax error
     17057     2F000 only select-into statement allowed
     17058     2F000 source-name of return-type is not record-type or record-type variable
     17059     2F000 source-name of rowtype must be a table, view, cursor, cursor-variable
     17060     2F000 a cursor-variable with having return-type cannot be used in OPEN FOR dynamic-sql
     17061     2F000 it can be allowed with only IN-Binding type
     17062     2F000 duplicated routine name
     17063     2F000 unknown routine name
     17064     2F000 invalid routine name
     17065     2F000 invalid routine object status(%s)
     17066     2F000 a RAISE statement with no exception name must be inside an exception handler
     17067     2F000 return types of Result Set variables or query do not match
     17068     2F000 wrong number or types of arguments
     17069     2F000 invalid variable usage
     17070     2F000 return statement in procedures or anonymous blocks cannot have <value> clause 
     17071     2F000 return statement in functions should have <value> clause
     17072     2F000 existing state of routine(%s) has been discarded
     17073     2F003 DDLs or DCLs cannot be invoked during DMLs or SELECT statements are executing in "%s"."%s"
     17074     2F003 cannot begin transaction inside a query in "%s"."%s"
     17075     2F003 cannot commit or rollback transaction inside a query or DML in "%s"."%s"
     17076     2F000 application error "%s"
     17077     2F000 the argument of collection type variable is not a constant expression
     17078     2F000 a function with OUT-Parameter not allowed in expression
     17079     2F000 a nested function not allowed in executing SQL
     17080     2F002 cannot execute DML jobs inside a query
     17081     2F000 program body of the routine is not defined
     17082     2F000 bind parameter in target or return clause is not allowed
     17083     2F000 Function "%s" returned without value
     17084     2F000 The argument "%s" of routine "%s" is invalid
     17085     2F000 a cursor (%s) already defined in package spec
     17086     2F000 a cursor or routine (%s) declared in spec must be defined in package body
     17087     2F000 existing state of package has been discarded
     17088     2F000 invalid package object status
     17089     2F000 cannot drop packages in use
     17090     2F000 Cursor Variables cannot be declared as part of a package
     17091     2F000 cannot perform nested updatable statements on cluster database
     17092     2F000 invalid package name
     17093     2F000 unsupported element data type
     17094     2F000 IN cursor cannot be OPENed
     18000     HY000 Invalid statement
     18001     HY024 Invalid attribute value
     18002     HY092 Invalid attribute/option identifier
     18003     42000 Transaction is READ ONLY
     18004     42000 Statement cannot execute as atomic action
     18005     42000 Preparable phase is open phase
     18006     08S01 Communication link failure
     18007     HYC00 not implemented feature, in a function %s
     18008     HY014 Limit on the number of SQL statement exceeded
     18009     42000 The command cannot be executed when global transaction is in the ACTIVE state
     18010     07009 Invalid descriptor index
     18011     HY000 Character set not equal(%s and %s)
     18012     HY010 fetch out of sequence
     18013     HYC00 Optional feature not implemented
     18014     07001 Wrong number of parameters
     18015     24000 Invalid cursor state
     18016     42000 remote xa transaction (%d.%ld) already exists
     18017     42000 remote xa transaction (%d.%ld) does not exist
     19000     HY009 Invalid use of null pointer
     19001     HY092 Invalid attribute/option identifier
     19002     08003 Connection not open
     19003     IM001 Driver does not support this function
     19004     IM004 Driver's SQLAllocHandle on SQL_HANDLE_ENV failed
     19005     IM005 Driver's SQLAllocHandle on SQL_HANDLE_DBC failed
     19006     08002 Connection name in use
     19007     HY090 Invalid string or buffer length
     19008     28000 Invalid authorization specification
     19009     HY010 Function sequence error
     19010     24000 Invalid cursor state
     19011     HY012 Invalid transaction operation code
     19012     HYC00 Optional feature not implemented
     19013     HY003 Invalid application buffer type
     19014     07009 Invalid descriptor index
     19015     HY004 Invalid SQL data type
     19016     HY105 Invalid parameter type
     19017     HY009 Invalid argument value
     19018     HY011 Attribute cannot be set now
     19019     HY024 Invalid attribute value
     19020     25000 Invalid transaction state
     19021     HY000 General error
     19022     07005 Prepared statement not a cursor-specification
     19023     22001 String data, right truncated
     19024     HY007 Associated statement is not prepared
     19025     HY092 Option type out of range
     19026     22002 Indicator variable required but not supplied
     19027     01S01 Error in row
     19028     HY016 Cannot modify an implementation row descriptor
     19029     HY091 Invalid descriptor field identifier
     19030     07006 Restricted parameter value violation
     19031     22015 Interval field overflow
     19032     22003 Numeric value out of range
     19033     01004 String data, right truncated
     19034     22018 Invalid character value for cast specification
     19035     01S07 Fractional truncation
     19036     22008 Datetime field overflow
     19037     22007 Invalid datetime format
     19038     08S01 Communication link failure
     19039     HY000 An invalid SQL type has occurred
     19040     34000 Invalid cursor name
     19041     HY000 Failed to atomic execution
     19042     HY110 Invalid driver completion
     19043     IM012 DRIVER keyword syntax error
     19044     08001 Client unable to establish connection
     19045     HY096 Information type out of range
     19046     IM002 Data source not found and no default driver specified
     19047     HY106 Fetch type out of range
     19048     HY100 Uniqueness option type out of range
     19049     HY101 Accuracy option type out of range
     19050     HY097 Column type out of range
     19051     HY098 Scope type out of range
     19052     HY099 Nullable type out of range
     19053     HY021 Inconsistent descriptor information
     19054     01S02 Option value changed
     19055     HY109 Invalid cursor position
     19056     HY107 Row value out of range
     19057     HYT00 Timeout expired
     19058     2C000 Invalid or unknown NLS parameter value specified
     19059     HY020 Attempt to concatenate a null value
     19060     HY019 Non-character and non-binary data sent in pieces
     19061     HY000 Invalid 'odbc.ini' specification. property : [%s] 
     19062     IM008 Dialog failed
     19063     40001 Transaction rollback
     19064     40003 Statement completion unknown
     19065     08S01 Communication link failure
     19066     01000 General warning
     19067     HY104 Invalid precision or scale value
     19068     40003 Retry the transactional operations
     19069     08S01 Failed to communicate with locator
     19070     08006 Unable to get cluster system information
     21000     HV000 Not used error
     21001     46001 Invalid connection url[%s]: [%s]
     21002     46110 Unsupported feature: [%s]
     21003     08S01 Invalid protocol: [%s]
     21004     HV000 Invalid method call for read-only ResultSet
     21005     08003 The connection is already closed
     21006     08003 The statement is already closed
     21007     08003 The ResultSet is already closed
     21008     HV000 Invalid method call for forward-only ResultSet
     21009     HV000 Invalid Wrapper type: [%s]
     21010     HV000 Invalid argument: [%s]
     21011     08000 Cannot connect to the server: %s
     21012     08S01 Communication link failure: %s
     21013     HV000 A mandatory property is omitted: [%s]
     21014     HV000 Not a select query for executeQuery method
     21015     HV000 The statement has produced a ResultSet
     21016     HV000 This method cannot be called for a PreparedStatement
     21017     HV000 Parameter type[%s] is mismatch with previous type[%s] during batch
     21018     HV000 Lack of parameter: [%s]'th parameter
     21019     HV000 No batch job added
     21020     HV000 Batch job added
     21021     22003 The value[%s] is out of range of [%s] type
     21022     22026 The value length is mismatch[%s != %s]
     21023     HV000 The value([%s] type) cannot be converted to [%s] type
     21024     08000 The connection timeout expired: [%s millis]
     21025     HV000 The column is not found: [%s]
     21026     3B000 Savepoint error: %s
     21027     HV000 Cannot execute the query in auto-commit mode
     21028     24000 Invalid cursor position
     21029     HV000 No column has been read
     21030     HV000 Encoding error: [%s]
     21031     HV000 Decoding error: [%s]
     21032     HV000 Stream error: [%s]
     21033     HV000 Trying to read the deleted row
     21034     HV000 Invalid interval format string: [%s]
     21035     HV000 The statement has an opened ResultSet
     21036     HV000 The RowId object is unknown
     21037     08000 The failover failed
     21038     07009 The parameterIndex is not valid: [%s]
     21039     HY000 No data read
     21040     HY000 Invalid locator protocol version
     21041     HY000 not matched locator protocol command sequence number
     21042     HY000 Unable to open the file '%s'
     21043     HY000 Unable to read the file '%s'
     21044     HY000 Unable to close the file '%s'
     21045     HY000 invalid INI file format
     21046     HY000 Parameter[%s]'s input data type is mismatched with output data type
     21047     40001 Retry the transactional operations again
     21048     08006 Unable to get cluster system information
     21049     HY000 The Statement does not have a ResultSet
     21050     08006 Unable to get location information
     21051     HY000 Not exist node information - %s
     23000     42000 syntax error
     23001     0A000 feature not supported
     23002     HY000 Bind variable "%s" was not declared
     23003     HY000 Application can't be initialized
     23004     HY000 Application can't be finalized
     23005     RD000 Service is not available
     23006     RD000 Statement did not prepared
     23007     08001 Client can't establish SQL-connection
     23008     HY000 cursor "%s" is not open
     23009     HY000 Application can't create semaphore
     23010     HY000 Application can't destroy semaphore
     23011     HY000 Application can't create allocator
     23012     HY000 Application can't destroy allocator
     23013     HY000 Application can't create symbol table
     23014     HY000 Application can't destroy symbol table
     23015     IM004 Driver's SQLAllocHandle on SQL_HANDLE_ENV failed
     23016     IM001 Driver does not support ODBC 3.0
     23017     HY000 Application can't allocate memory
     23018     42000 Statement "%s" was not prepared
     23019     42000 Descriptor name is too long
     23020     HYC00 Not implemented feature, in a function %s
     23021     07004 USING clause required for dynamic paramters
     23022     07001 USING clause: illegal variable name/number
     23023     07001 USING clause: not all variables bound
     23024     07007 INTO clause required for result fields
     23025     07001 INTO clause: illegal variable name/number
     23026     07001 INTO clause: not all variables bound
     23027     22002 null value, no indicator parameter
     23028     07005 cusor "%s" statement is not a query
     23029     08003 connection not open
     23030     34000 cursor "%s" is not updatable
     23031     08002 connection name "%s" in use
     23032     08002 duplicate connection context
     23033     HY000 GROUPID type is only available with global connection
     23034     42000 SELECT INTO returns too many rows
     23035     24000 cursor "%s" is not declared
     23036     24000 cursor "%s" is not closed
     23037     24000 cursor "%s" is already opened
     24000     08S01 Communication link failure
     24001     08S01 Invalid communication protocol
     24002     22000 Invalid GOLDILOCKS_DATA directory
     24003     22000 not supported function
     24004     22000 Invalid interprocess protocol
     24005     22000 Unable to attach the shared memory segment. unable to access the file '%s'
     24006     HV090 Invalid string length or buffer length
     24007     22000 not matched command sequence number
     25000     0A000 feature not supported
     25001     HY000 Server is not running
     25002     HY000 Environment Variable "%s" is not defined.
     25003     08000 Invalid protocol
     25004     HY000 Startup must be executed in dedicated session
     25005     HY000 session killed
     25006     HY000 remote session is not opened
     25007     42000 the property '%s' of cluster member '%s' is not compatible with the cluster system
     25008     42000 the scn '%s' of cluster member '%s' is mismatch
     25009     HY000 number of shared servers must be greater than or equal to number of request queues
     25010     HY000 internal error ( %s, %d )
     40000     42000 syntax error
     40001     0A000 feature not supported
     40002     HY000 Bind variable "%s" not declared
     40003     42000 "%s": table or view does not exist.
     40004     42000 "%s": index does not exist.
     40005     RD000 Service is not available.
     40006     RD000 Statement did not prepared.
     40007     42000 '%s': duplicate statement
     40008     42000 '%s': statement does not exist
     40009     42000 '%s': statement is not prepared
     40010     42000 insufficient privileges
     40011     42000 driver does not support %s function
     40012     42000 invalid ojbect for describe
     40013     42000 driver does not support the requested connection mode( %s )
     40014     40000 the rollback was caused by an unspecified reason
     40015     40000 the rollback was caused by a communication failure
     40016     40001 a deadlock was detected
     40017     40002 a condition that violates the integrity of the resources was detected
     40018     40000 the resource manager rolled back the transaction branch for a reason not on this list
     40019     HY000 a protocol error occurred in the resource manager
     40020     HY000 a transaction branch took too long
     40021     HY000 may retry the transaction branch
     40022     HY000 the inclusive upper bound of the rollback codes
     40023     HY000 resumption must occur where suspension occurred
     40024     HY000 the transaction branch may have been heuristically completed
     40025     HY000 the transaction branch has been heuristically committed
     40026     HY000 the transaction branch has been heuristically rolled back
     40027     HY000 the transaction branch has been heuristically committed and rolled back
     40028     HY000 routine returned with no effect and may be re-issued
     40029     HY000 the transaction branch was read-only and has been committed
     40030     HY000 asynchronous operation already outstanding
     40031     HY000 a resource manager error occurred in the transaction branch
     40032     HY000 the XID is not valid
     40033     HY000 invalid arguments were given
     40034     HY000 routine invoked in an improper context
     40035     HY000 resource manager unavailable
     40036     HY000 the XID already exists
     40037     HY000 resource manager doing work outside transaction
     40038     HY000 unknown xa error
     40039     HY000 marked the transaction branch rollback-only for unspecified reason
     40040     HY000 cannot open the resource
     40041     HY000 cannot close the resource
     40042     HY000 the sql is empty
     40043     HY000 invalid host variable type
     40044     08003 connection does not exist
     40045     HY000 invalid NUMSIZE value: NUMSIZE must be between %d and %d
     40046     HY000 invalid PAGESIZE value: PAGESIZE must be between %d and %d
     40047     HY000 invalid LINESIZE value: LINESIZE must be between %d and %d
     40048     HY000 invalid COLSIZE value: COLSIZE must be between %d and %d
     40049     HY000 invalid HISTORY value: HISTORY must be less equal than %d
     40050     HY000 invalid DDLSIZE value: DDLSIZE must be between %d and %d
     40051     HY000 invalid object identifier
     40052     HY000 not enough DDLSIZE. 
use command: \set ddlsize {n}
     40053     HY000 confirmation password mismatch
     40054     HY000 invalid locator ini property - '%s'
     40055     HY000 not exist member '%s' in file - '%s' 
     40056     HY000 some of nodes were failed to startup
     40057     HY000 not specified valid location information
     40058     HY000 some of nodes were failed to shutdown
     40059     HY000 failied to connect to original driver node '%s' after startup
     40060     HY000 cannot execute 'cstartup' or 'cshutdown' command in DA mode
     40061     HY000 currently connected node is inactive
     40062     HY000 file not exist -'%s'
     41000     42000 syntax error at line %d, in file %s
     41001     0A000 feature not supported
     41002     42000 Host variable "%s" not declared
     41003     42000 Cursor "%s" not declared
     41004     42000 "%s": file not exist
     41005     42000 expression type does not match usage
     41006     42000 Fatal error while doing embedded SQL precompiling
     41007     HY000 Precompiler can't create symbol table
     41008     HY000 Precompiler can't destroy symbol table
     41009     42000 identifier is too long
     41010     42000 token "%s" is not valid in preprocessor expressions
     41011     42000 multi-character character constant
     41012     42000 floating constant in preprocessor expression
     41013     42000 invalid suffix "%s" on integer constant
     41014     42000 cursor name "%s" already declared
     41015     07004 cursor "%s" is not a dynamic cursor
     41016     42000 "%s" has no member named "%s"
     41017     42000 storage size of "%s" isn't known
     41018     42000 variable "%s" must be integer type
     41019     42000 variable "%s" must be string type
     41020     42000 invalid indicator variable type: indicator variable "%s" must have numeric type(char/short/int/long)
     41021     42000 duplicate "%s"
     41022     42000 both "%s" and "%s" in declaration specifiers
     41023     42000 two or more data types in declaration specifiers
     41024     42000 C++ punctuation sequences are not permitted
     41025     42000 host variable expression has invalid type
     41026     42000 typedef "%s" has invalid
     41027     42000 too many 'define' macro (%d)
     41028     42000 '%s' macro is already defined at line %d, in file %s
     41029     42000 missing host variable
     41030     42000 invalid getting groupid variable type: variable "%s" must have signed numeric type
     41031     42000 invalid sql statement: getting groupid is available with select/update/delete/insert statement
     42000     RD000 Service is not available
     42001     HY000 invalid control file format
     42002     HY000 buffer exceeded overflow area
     42003     HY000 open same file(%s)
     42004     HY000 occur invalid handle error
     42005     HY000 occur error while operating SQLGetDiagRec/SQLGetDiagField
     42006     HY000 using same character for delimiter and qualifier
     42007     HY000 invalid thread unit count.(1~32)
     42008     HY000 invalid array size.(1~65535)
     42009     HY000 unavailable multithreading in export mode.
     42010     08S01 Communication link failure
     42011     HY000 invalid file size (minimum size : %ld)
     42012     HY000 unavailable file size in text mode.
     42013     HY000 invalid column type - (%d)
     42014     HY000 invalid column count.
     42015     HY000 invalid data size.
     42016     HY000 invalid header of binary file.
     42017     HY000 file is empty.
     42018     HY000 Qualifier must be 1 length character.
     42019     HY000 LF and CR can not be used for delimiter or qualifier.
     42020     HY000 qualifiers and terminators must not be subsets of each other
     42021     HY000 table name must be given in case of absence of control file.
     42022     HY000 can not fetch schema name.
     42023     22001 byte length of data greater than column length.
     42024     HY000 invalid direct io size
     44000     HY000 database is already mounted
     44001     HY000 database is already local opened
     44002     HY000 database is already opened
     44003     HY000 system thread is already created
     44004     HY000 failed to create system threads (%s)
     44005     HY000 member '%s' does not exist
     44006     HY000 fail to send packet through communication context
     44007     HY000 failed to start up a process '%s'
     45000     HY000 Listener configuration file "%s" doesn't exist.
     45001     HY000 Environment variable "%s" is not defined.
     45002     HY000 Listener is already started.
     45003     HY000 overflow fd
     45004     08000 Invalid communication protocol
     45005     08004 access denied
     45006     HY000 Operation timed out
     45007     HY000 shared mode inactive
     45008     HY000 Invalid property value [ DEDICATED | SHARED ] : %s
     45009     HY000 Invalid property value [ NO | INVITED | EXCLUDED ] : %s
     45010     HY000 Invalid property value [ YES | NO | 1 | 0 ]: %s
     45011     HY000 Invalid property value [ %ld ~ %ld ]: %s 
     45012     HY000 Invalid property value [ %ld ~ %ld ]: %s 
     45013     HY000 buffer overflow %s 
     46000     RD000 Service is not available
     46001     HY000 "%s": file does not exist
     46002     HY000 configure file processing error
     46003     HY000 "%s": table does not exist
     46004     HY000 "%s": schema does not exist
     46005     HY000 "%s.%s": previously added. maybe duplicated
     46006     HY000 "%s%s": table must have a primary key
     46007     HY000 internal error occurred (%s)
     46008     HY000 invalid datatype (%ld)
     46009     HY000 "%s.%s": table must set supplemental log or primary key.
     46010     HY000 group [%s] is already running
     46011     HY000 cyclone is not running
     46012     HY000 GOLDILOCKS_DATA system environment is invalid
     46013     HY000 "%s" log file is reused or invalid: restart cyclone with '--reset' option
     46014     HY000 failed to analyze flow [%s]
     46015     HY000 Invalid port number (1024 ~ 49151) [%s]
     46016     HY000 Communication link failure
     46017     HY000 Invalid protocol value (%s)
     46018     HY000 Master disconnect abnormally
     46019     HY000 Protocol error occurred (%s)
     46020     HY000 Already slave connected
     46021     HY000 Invalid transaction slot ID
     46022     HY000 Invalid supplemental log (%d)
     46023     HY000 Invalid operation for DDL
     46024     HY000 Invalid value to analyze
     46025     HY000 Invalid group name (%s)
     46026     HY000 Not set master ip
     46027     HY000 Invalid capture information
     46028     HY000 There is no group in configure
     46029     HY000 Duplicate group name (%s)
     46030     HY000 Invalid Value : %s(%s)
     46031     HY000 Too low value : %s(%ld)
     46032     HY000 Invalid host port (%d)
     46033     HY000 Redo log file read timeout (%s)
     46034     HY000 Invalid archive log file (%s)
     46035     HY000 Invalid temporary file (%s)
     46036     HY000 failed to write file (%s)
     46037     HY000 failed to update state (%s)
     46038     HY000 failed to set propagate mode at session
     46039     HY000 There is no active redo log file.
     46040     HY000 There is no restart information. master database must be started first.
     46041     HY000 Cannot add new table. master database must be started first. (%s.%s)
     46042     HY000 Master database must be started(Open status) for the first time, reset table, sync or recovery.
     46043     HY000 Meta file has broken. please restart with '--reset all'(%s)
     46044     HY000 Redo log file does not exist (%s).
     46045     HY000 USER_ID or USER_PW does not exist.
     46046     HY000 Slave is not running with --sync option or already sync.
     46047     HY000 Invalid connect information for sync (%s)
     46048     HY000 (%s) value is too long
     46049     HY000 Invalid encrypt/decrypt key
     46050     HY000 no '--key' option
     46051     HY000 password already exists (use one of USER_PW or USER_ENCRYPT_PW)
     46052     HY000 reset or sync table (%s.%s) has never participated in replication
     46053     HY000 reset or sync argument is invalid (%s)
     46054     HY000 Table meta file has broken. please restart with '--reset all'
     46055     HY000 protocol timeout
     46056     HY000 Slave stopped normally
     46057     HY000 Cannot use reset and sync option at the same time.
     46058     HY000 There is no (%s.%s) table to sync (--sync option)
     46059     HY000 (%s.%s) table (%s) column is not acceptable(GENERATED ALWAYS AS IDENTITY)
     46060     HY000 driver does not support %s function
     46061     HY000 data type is not supported.
     46062     HY000 Cluster information does not matched( before groupid(%d), memberid(%d)/current groupid(%d), memberid(%d) )
     46063     HY000 Invalid cluster information at configure file( %s )
     46064     HY000 Fail to rollback transaction
     46065     HY000 Slave is running with --sync option
     46066     HY000 MYSQL_DATABASE configuration must needed to connect MySQL/MariaDB
     47000     RD000 Service is not available
     47001     HY000 Invalid protocol value (%s)
     47002     HY000 "%s": file does not exist
     47003     HY000 configure file processing error
     47004     HY000 invalid control file
     47005     HY000 Communication link failure
     47006     HY000 LogMirror is already running
     47007     HY000 GOLDILOCKS_DATA system environment is invalid
     47008     HY000 There is no shared memory area for LogMirror
     47009     HY000 Invalid value : %s(%s)
     47010     HY000 Invalid port : (%ld)
     47011     HY000 Master disconnect abnormally
     47012     HY000 Invalid log file(%s)
     47013     HY000 Archive log file does not exist
     47014     HY000 Archive log file read timeout (%s)
     47015     HY000 LogMirror is not running
     47016     HY000 Connection information does not exist
     47017     HY000 Infiniband receive fail. (%ld)
     47018     HY000 GOLDILOCKS Shutdown or give-up LogMirror Service.
     47019     HY000 Invalid encrypt/decrypt key
     47020     HY000 no '--key' option
     47021     HY000 password already exists(use one of USER_PW or USER_ENCRYPT_PW)
     47022     HY000 protocol heartbeat timeout
     48000     HY000 GOLDILOCKS_DATA system environment is invalid
     48001     HY000 "%s": file does not exist
     48002     RD000 Service is not available
     48003     HY000 configure file processing error
     48004     HY000 Duplicate group name (%s)
     48005     HY000 Invalid value : %s(%ld)
     48006     HY000 Invalid group name
     48007     HY000 Invalid port number (1 ~ 65535)
     48008     HY000 There is no group in configure
     48009     HY000 cymon is already running
     48010     HY000 Communication link failure
     48011     HY000 Protocol error occurred (%s)
     48012     HY000 Already monitor connected
     48013     HY000 cymon is not running
     48014     HY000 internal error occurred (%s)
     48015     HY000 Fail to update monitoring info.
     48016     HY000 USER_ID or USER_PW does not exist.
     48017     HY000 Invalid encrypt/decrypt key
     48018     HY000 no '--key' option
     48019     HY000 password already exists(use one of USER_PW or USER_ENCRYPT_PW)
     50000     HY000 Dispatcher is already started.
     50001     HY000 overflow fd
     51000     HY000 overflow fd
     52000     08S01 Communication link failure
     52001     08000 Invalid communication protocol
     52002     HY000 Not enough cm unit memory
     52003     HY000 exceeded maximum packet allocation timeout
     53000     HY000 invalid phase(%s): executable phase is %s
     53001     HY000 GOLDILOCKS_DATA system environment is invalid
     53002     HY000 gmaster is active
     53003     HY000 gsyncher is already running
     53004     HY000 Shared memory is cleared
     56000     HY000 location information of member '%s' already exists
     56001     HY000 location information of member '%s' does not exist
     56002     HY000 location information of member '%s' is modified by concurrent execution
     56003     HY000 has inactive member ( %s )
     56004     HY000 location file is corrupted - '%s'
     56005     HY000 connections of some cluster members are broken
     56006     40000 transaction rollback: failed to prepare global transaction
     56007     HY000 must be accessable to at least one of replicas
     56008     40000 transaction rollback: failed to synchronize replicas
     56009     HY000 remote server ( member ID: %ld ) is abnormally terminated
     56010     40000 transaction rollback: remote session is abnormally terminated
     56011     HY000 a shared session cannot modify NUMA property
     56012     HY000 no connection was established to recover in-doubt transactions
     56013     HY000 cannot resolve in-doubt transaction '%d.%d.%ld' because '%d' members of the total '%d' remote cluster members were disconnected - connection map was '%s'
     56014     HY000 MAX_NODE_COUNT property value '%d' must be equal to or less than '%d'
     56015     HY000 '%s' property value must be greater than or equal to '%s' property value '%d'
     56016     HY000 all members affected by the transaction are inactive - cannot guarantee durability of the transaction
     56017     40000 transaction rollback: failed to open remote session
     56018     HY000 protocol payload size(%ld) exceed maximum packet size(%ld)
     56019     HY000 failover busy
     56020     HY000 internal error ( %s, %d )
     56021     HY000 exceeded maximum response timeout
     56022     HY000 failed to connect to an host
     56023     HY000 invalid cluster communication protocol
     56024     HY000 sequence '%s' is offline
     56025     HY000 cannot synchronize because some members were disconnected
     56026     HY000 identity column '%s' of table '%s' is offline
     56027     HY000 cannot resolve in-doubt transaction '%d.%d.%ld' because the transaction remains unfinished
     56028     HY000 the property '%s' is not compatible with the cluster system
     57000     HY000 invalid statement
     58000     HY000 the sender failed to connect to the member(%d)
     58001     HY000 the socket of target member '%s' is already disconnected
     58002     HY000 the location information for member '%s' is not found
     58003     HY000 the connection information is invalid; %s %d is either equal to or greater than %d
     58004     HY000 the connection timeout from remote(%d) - %s
     58005     HY000 the disconnection timeout from remote(%d)
     58006     HY000 invalid connection state transition
     58007     HY000 cluster dispatcher thread count does not match
     58008     HY000 failed to start '%s' thread of cluster dispatcher
     58009     HY000 internal error ( %s, %d )
     58010     HY000 broken socket
     58011     HY000 old cluster connection is still alive
     58012     HY000 failover event is in progress
     58013     HY000 the connection can be established at LOCAL OPEN or OPEN phase
     58014     HY000 old cluster sessions are still alive
     59000     HY000 exceeded port cnt
     59001     HY000 gtrclogger is already running
     59002     HY000 gtrclogger is not running
     59003     HY000 Operation timed out
     59004     22000 Invalid GOLDILOCKS_DATA directory
     60000     HY000 syntax error
     60001     HY000 file does not exist - '%s'
     60002     HY000 GOLDILOCKS_DATA system environment is invalid
     60003     HY000 Invalid value - %s(%s)
     60004     HY000 file name is too long - '%s'
     60005     HY000 glocator is already started.
     60006     HY000 Location file is corrupted - '%s'
     60007     HY000 Property value is out of length - '%s'
     60008     HY000 Invalid property value [ YES | NO | 1 | 0 ] - '%s' 
     60009     HY000 Invalid property value [ %ld ~ %ld ] - '%s' 
     60010     HY000 Invalid property value [ %ld ~ %ld ] - '%s' 
     60011     HY000 File is already exist - '%s' 
     60012     HY000 Location file exceeded max size(%ld) - over size(%ld)
     60013     HY000 Not exist node information - '%s'
     60014     HY000 Exceeded response time for failover.
     60015     HY000 Node is on failover - '%s'
     60016     HY000 Need more alternate locator host information.
     60017     HY000 Invalid configure file specifcation - property:[%s]
     60018     HY000 Failed to propagate - '%s:%d'
     60019     HY000 Not exist service information - '%s'
     60020     HY000 '%s' node is already connected.
     60021     HY000 overflow fd.
     61000     HY000 Syntax error
     61001     HY000 File is not exist - '%s'
     61002     HY000 Can not find any ini object in file - '%s'
     61003     HY000 Dsn is not exist - '%s'
     61004     HY000 ADD MEMBER keyword syntax is error - '%s'
     61005     HY000 ADD SERVICE keyword syntax is error - '%s'
     61006     HY000 Invalid property value [ YES | NO | 1 | 0 ] - '%s' 
     61007     HY000 Invalid property value [ %ld ~ %ld ] - '%s' 
     61008     HY000 Invalid property value [ %ld ~ %ld ] - '%s' 
     61009     HY000 GOLDILOCKS_DATA system environment is invalid
     61010     HY000 Keyword syntax is invalid - '%s'
     61011     HY000 Data value is invalid - '%s'
     62000     HY000 gmon is already running
     62001     HY000 process(%ld) did not respond signal
     62002     HY000 GOLDILOCKS_DATA system environment is invalid
     63000     HY000 GOLDILOCKS_DATA system environment is invalid
     63001     HY000 Property value is out of length - '%s'
     63002     HY000 Invalid property value [ YES | NO | 1 | 0 ] - '%s' 
     63003     HY000 Invalid property value [ %ld ~ %ld ] - '%s' 
     63004     HY000 Invalid property value [ %ld ~ %ld ] - '%s' 
     63005     HY000 gagent is already started.
     63006     HY000 file name is too long - '%s'
     63007     HY000 file does not exist - '%s'
     63008     HY000 Database is not cluster.
     63009     HY000 Invalid configure file specifcation - property:[%s]
     63010     HY000 Invalid phase(%s): executable phase is between %s and %s
     63011     HY000 Property PORT of dsn(%s) is not set in file 'odbc.ini'
     63012     08000 Timeout expired.
     63013     HYT00 Unable to establish connection.
     64000     RD000 Service is not available
     64001     HY000 "%s": file does not exist
     64002     HY000 configure file processing error
     64003     HY000 "%s": table does not exist
     64004     HY000 "%s": schema does not exist
     64005     HY000 "%s.%s": previously added. maybe duplicated
     64006     HY000 "%s%s": table must have a primary key
     64007     HY000 internal error occurred (%s)
     64008     HY000 invalid datatype (%ld)
     64009     HY000 "%s.%s": table must set supplemental log or primary key.
     64010     HY000 group [%s] is already running
     64011     HY000 cyfile is not running
     64012     HY000 GOLDILOCKS_DATA system environment is invalid
     64013     HY000 "%s" log file is reused or invalid: restart cyfile with '--reset' option
     64014     HY000 failed to analyze flow [%s]
     64015     HY000 Invalid transaction slot ID
     64016     HY000 Invalid operation for DDL
     64017     HY000 Invalid group name (%s)
     64018     HY000 Invalid capture information
     64019     HY000 There is no group in configure
     64020     HY000 Duplicate group name (%s)
     64021     HY000 Invalid Value : %s(%s)
     64022     HY000 Invalid host port (%s)
     64023     HY000 Redo log file read timeout (%s)
     64024     HY000 Invalid archive log file (%s)
     64025     HY000 failed to write file (%s)
     64026     HY000 failed to set propagate mode at session
     64027     HY000 There is no active redo log file.
     64028     HY000 Cannot add new table. master database must be started first. (%s.%s)
     64029     HY000 Master database must be started(Open status) for the first time, reset table.
     64030     HY000 Meta file has broken. please restart with '--reset all'(%s)
     64031     HY000 Redo log file does not exist (%s).
     64032     HY000 USER_ID or USER_PW does not exist.
     64033     HY000 (%s) value is too long
     64034     HY000 Invalid encrypt/decrypt key
     64035     HY000 no '--key' option
     64036     HY000 password already exists (use one of USER_PW or USER_ENCRYPT_PW)
     64037     HY000 reset or sync table (%s.%s) has never participated in replication
     64038     HY000 reset or sync argument is invalid (%s)
     64039     HY000 Table meta file has broken. please restart with '--reset all'
     64040     HY000 (%s.%s) table (%s) column is not acceptable(GENERATED ALWAYS AS IDENTITY)
     64041     HY000 data type is not supported.(%s)
     64042     HY000 Cluster information does not matched( before groupid(%d), memberid(%d)/current groupid(%d), memberid(%d) )
     64043     HY000 Invalid cluster information at configure file( %s )
     64044     HY000 Control has broken(CRC Error)( %s )
     64045     HY000 Control has broken(internal CRC Error)( %s )

