apiVersion: v1
kind: PersistentVolume
metadata:
  name: goldilocks-pv-claim
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /home/goldilocks
