apiVersion: v1
kind: PersistentVolume
metadata:
  name: goldilocks-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/son_kube/ymal/goldilocks/goldilocks"
