apiVersion: v1
kind: Template
metadata:
  name: test-template
  annotations:
    description: "Description"
    iconClass: "icon-redis"
    tags: "database,rdbms"
objects:
- apiVersion: v1
  kind: Service
  metadata:
    name: nginx
    labels:
      app: nginx
  spec:
    ports:
    - port: 80
      name: web
    clusterIP: None
    selector:
      app: nginx
- apiVersion: apps/v1beta1
  kind: StatefulSet
  metadata:
    name: web
  spec:
    selector:
      matchLabels:
        app: nginx # .spec.template.metadata.labels 와 일치해야 한다
    serviceName: "nginx"
    replicas: 3 # 기본값은 1
    minReadySeconds: 10 # 기본값은 0
    template:
      metadata:
        labels:
          app: nginx # .spec.selector.matchLabels 와 일치해야 한다
      spec:
        terminationGracePeriodSeconds: 10
        containers:
        - name: nginx
          image: k8s.gcr.io/nginx-slim:0.8
          ports:
          - containerPort: 80
            name: web
          volumeMounts:
          - name: www
            mountPath: /usr/share/nginx/html
    volumeClaimTemplates:
    - metadata:
        name: www
      spec:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: "my-storage-class"
        resources:
          requests:
            storage: 1Gi
parameters:
- description: Password used for goldilocks authentication
  from: '[A-Z0-9]{8}'
  generate: expression
  name: SYS_PASSWORD
- description: Password used for goldilocks authentication
  from: '[A-Z0-9]{8}'
  generate: expression
  name: MEMBER_COUNT
- description: Password used for goldilocks authentication
  from: '[A-Z0-9]{8}'
  generate: expression
  name: GROUP_COUNT



