--######################################################################################
-- View For Sequence And Identity Column
--
-- MEMBER_NAME    : Cluster Member Name
-- MODE           : Identity Column Or Sequence
-- TAB_OWN_NAME   : Table Name(Identity Column), Owner(Sequence)
-- COL_SEQ_NAME   : Column Name(Identity Column), Sequence Name(Sequence)
-- LOC_CURR_VALUE : Current Value In Local
-- LOC_NEXT_VALUE : Next Value In Local
-- GLO_NEXT_VALUE : Next Value In Cluster
-- RESTART_VALUE  : Restart Value
-- INCREMENT      : Increment
-- MINVALUE       : Min Value
-- MAXVALUE       : Max Value
-- ALTER_NEXT_SQL : Alter Next SQL
--
--gSQL> SELECT * FROM TECH_SEQUENCE;
--
--MEMBER_NAME MODE     TAB_OWN_NAME COL_SEQ_NAME LOC_CURR_VALUE LOC_NEXT_VALUE GLO_NEXT_VALUE RESTART_VALUE INCREMENT MINVALUE            MAXVALUE ALTER_NEXT_SQL                               
------------- -------- ------------ ------------ -------------- -------------- -------------- ------------- --------- -------- ------------------- ---------------------------------------------
--G1N1        SEQUENCE TEST         S1                        2              3             21            21         1        1 9223372036854775807 ALTER SEQUENCE S1 RESTART WITH 3             
--G2N1        SEQUENCE TEST         S1                        1              1             21            21         1        1 9223372036854775807 ALTER SEQUENCE S1 RESTART WITH 1             
--G2N1        IDENTITY T1           C1                        1              2             21            21         1        1 9223372036854775807 ALTER TABLE T1 ALTER COLUMN C1 RESTART WITH 2
--G1N1        IDENTITY T1           C1                        1              2             21            21         1        1 9223372036854775807 ALTER TABLE T1 ALTER COLUMN C1 RESTART WITH 2
--######################################################################################

DROP VIEW IF EXISTS PERFORMANCE_VIEW_SCHEMA.TECH_SEQUENCE;

CREATE VIEW PERFORMANCE_VIEW_SCHEMA.TECH_SEQUENCE
(
  MEMBER_NAME,
  MODE,
  TAB_OWN_NAME,
  COL_SEQ_NAME,
  LOC_CURR_VALUE,
  LOC_NEXT_VALUE,
  GLO_NEXT_VALUE,
  RESTART_VALUE,
  INCREMENT,
  MINVALUE,
  MAXVALUE,
  ALTER_NEXT_SQL
)
AS
SELECT
  NVL(AU.CLUSTER_MEMBER_NAME, 'STANDALONE') MEMBER_NAME,
  'SEQUENCE' AS MODE,
  AU.AUTHORIZATION_NAME OWNER,
  DSS.SEQUENCE_NAME SEQ_NAME,
  XS.LOCAL_CURR_VALUE LOC_CURR_VALUE,
  XS.LOCAL_NEXT_VALUE LOC_NEXT_VALUE,
  XS.GLOBAL_NEXT_VALUE GLO_NEXT_VALUE,
  XS.RESTART_VALUE,
  XS.INCREMENT_BY INCREMENT,
  XS.MINVALUE MINVALUE,
  XS.MAXVALUE MAXVALUE,
  'ALTER SEQUENCE ' || DSS.SEQUENCE_NAME || ' RESTART WITH ' || XS.LOCAL_NEXT_VALUE || ';' AS ALTER_NEXT_SQL
FROM
  AUTHORIZATIONS@GLOBAL[IGNORE_INACTIVE_MEMBER] AU,
  X$SEQUENCE@GLOBAL[IGNORE_INACTIVE_MEMBER] XS,
  DEFINITION_SCHEMA.SEQUENCES@GLOBAL[IGNORE_INACTIVE_MEMBER] DSS
WHERE
  1 = 1 AND
  NVL(AU.CLUSTER_MEMBER_NAME, 'STANDALONE') = NVL(XS.CLUSTER_MEMBER_NAME, 'STANDALONE') AND
  NVL(AU.CLUSTER_MEMBER_NAME, 'STANDALONE') = NVL(DSS.CLUSTER_MEMBER_NAME, 'STANDALONE') AND
  NVL(XS.CLUSTER_MEMBER_NAME, 'STANDALONE') = NVL(DSS.CLUSTER_MEMBER_NAME, 'STANDALONE') AND
  AU.AUTH_ID = OWNER_ID AND
  XS.PHYSICAL_ID = DSS.PHYSICAL_ID
UNION ALL
SELECT
  NVL(DST.CLUSTER_MEMBER_NAME, 'STANDALONE') MEMBER_NAME,
  'IDENTITY' AS MODE,
  DST.TABLE_NAME,
  DSW.COLUMN_NAME,
  XS.LOCAL_CURR_VALUE,
  XS.LOCAL_NEXT_VALUE,
  XS.GLOBAL_NEXT_VALUE,
  XS.RESTART_VALUE,
  XS.INCREMENT_BY,
  XS.MINVALUE,
  XS.MAXVALUE,
  'ALTER TABLE ' || DST.TABLE_NAME || ' ALTER COLUMN ' || DSW.COLUMN_NAME || ' RESTART WITH ' || XS.LOCAL_NEXT_VALUE || ';' AS ALTER_NEXT_SQL
FROM
  X$SEQUENCE@GLOBAL[IGNORE_INACTIVE_MEMBER] XS ,
  DICTIONARY_SCHEMA.WHOLE_COLUMNS@GLOBAL[IGNORE_INACTIVE_MEMBER] DSW,
  DEFINITION_SCHEMA.TABLES@GLOBAL[IGNORE_INACTIVE_MEMBER] DST
WHERE
  1 = 1 AND
  NVL(DST.CLUSTER_MEMBER_NAME, 'STANDALONE') = NVL(XS.CLUSTER_MEMBER_NAME, 'STANDALONE') AND
  XS.PHYSICAL_ID = DSW.IDENTITY_PHYSICAL_ID AND
  DSW.OWNER_ID = DST.OWNER_ID AND
  DSW.SCHEMA_ID = DST.SCHEMA_ID AND
  DSW.TABLE_ID = DST.TABLE_ID AND
  DSW. OWNER_ID != 1
ORDER BY 2, 3, 1, 4;

GRANT SELECT ON TABLE PERFORMANCE_VIEW_SCHEMA.TECH_SEQUENCE TO PUBLIC;