{{ define "goldilocks-master-service" -}}
---


apiVersion: v1
kind: PersistentVolume
metadata:
  name: goldilocks-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/son_kube/ymal/goldilocks/goldilocks"


apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: goldilocks-pvc-volume
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi



---
{{- end -}}

