{{ range $member := $.Values.topology.groups }}

{{- if $member.persistence.enabled }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ $member.persistence.pvc_name }}
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ $member.persistence.storage }}
---
{{- end }}
{{ end }}
