--###################################################
--# CREATE TABLE: simple example
--###################################################

--# result: success
DROP TABLE IF EXISTS t1;
COMMIT;

--# result: success
CREATE TABLE t1 
( 
    id     NUMBER
  , name   VARCHAR(128) 
);
COMMIT;


--# result: 1 row
INSERT INTO t1 VALUES ( 1, 'anonymous' );

--# result: 1 row
INSERT INTO t1 VALUES ( 2, 'someone' );
COMMIT;

--# result: 2 rows
--#        1   anonymous
--#        2   someone
SELECT * FROM t1 ORDER BY id;



--# result: success
DROP TABLE t1;
COMMIT;



--###################################################
--# CREATE TABLE: with <table_name>
--###################################################

--# result: success
DROP TABLE IF EXISTS public.t1;
COMMIT;

--# result: success
CREATE TABLE public.t1 
( 
    id     NUMBER
  , name   VARCHAR(128) 
);
COMMIT;


--# result: success
DROP TABLE public.t1;
COMMIT;


--###################################################
--# CREATE TABLE: with <data type>
--###################################################

--# result: success
DROP TABLE IF EXISTS t1;
COMMIT;

--# result: success
CREATE TABLE t1 
( 
    c01    VARCHAR(128)
  , c02    VARBINARY(128)
  , c03    NUMERIC(38,20)
  , c04    FLOAT(126)
  , c05    BOOLEAN
  , c06    TIMESTAMP
  , c07    INTERVAL DAY(4) TO SECOND(6)
);
COMMIT;


--# result: success
DROP TABLE t1;
COMMIT;


--###################################################
--# CREATE TABLE: with <character length units>
--###################################################

--# result: success
DROP TABLE IF EXISTS t1;
COMMIT;

--# result: success
CREATE TABLE t1 
( 
    id      BIGINT
  , name    VARCHAR(  128 CHARACTERS )
  , addr    VARCHAR( 1024 OCTETS )
);
COMMIT;


--# result: success
DROP TABLE t1;
COMMIT;


--###################################################
--# CREATE TABLE: with <default clause>
--###################################################


--# result: success
CREATE TABLE t1 
( 
    id     NUMBER        DEFAULT 0 
  , name   VARCHAR(128)  DEFAULT 'anonymous'
  , addr   VARCHAR(1024) DEFAULT NULL 
);
COMMIT;



--# result: 1 row
INSERT INTO t1 DEFAULT VALUES;

--# result: 1 row
INSERT INTO t1 VALUES( 1, DEFAULT, 'anywhere' );

--# result: 1 row
INSERT INTO t1 VALUES( 2, 'someone', 'somewhere' );
COMMIT;



--# result: 3 rows
--#        0    anonymous   null
--#        1    anonymous   anywhere
--#        2    someone     somewhere
SELECT * FROM t1 ORDER BY id;



--# result: success
DROP TABLE t1;
COMMIT;



--###################################################
--# CREATE TABLE: with <identity column specification>
--###################################################


--# result: success
CREATE TABLE t1 
( 
    id     NUMBER        GENERATED BY DEFAULT AS IDENTITY 
  , name   VARCHAR(128)
  , addr   VARCHAR(1024) 
);
COMMIT;



--# result: 1 row
INSERT INTO t1 DEFAULT VALUES;

--# result: 1 row
INSERT INTO t1 VALUES( DEFAULT, 'anyone', 'anywhere' );

--# result: 1 row
INSERT INTO t1 VALUES( DEFAULT, 'someone', 'somewhere' );
COMMIT;



--# result: 3 rows
--#        1    null        null
--#        2    anyone      anywhere
--#        3    someone     somewhere
SELECT * FROM t1 ORDER BY id;



--# result: success
DROP TABLE t1;
COMMIT;


--###################################################
--# CREATE TABLE: with <column constraint definition>
--###################################################


--# result: success
CREATE TABLE t1 
( 
    id     NUMBER        PRIMARY KEY
  , name   VARCHAR(128)  NOT NULL
  , addr   VARCHAR(1024) 
);
COMMIT;



--# result: success
DROP TABLE t1;
COMMIT;


--###################################################
--# CREATE TABLE: with <index name clause>
--###################################################

--# result: success
CREATE TABLE t1 
( 
    id     NUMBER        PRIMARY KEY INDEX t1_pk 
  , name   VARCHAR(128)  NOT NULL
  , addr   VARCHAR(1024) 
);
COMMIT;


--# result: success
DROP TABLE t1;
COMMIT;



--###################################################
--# CREATE TABLE: with <table constraint definition>
--###################################################


--# result: success
CREATE TABLE t1 
( 
    id     NUMBER        
  , name   VARCHAR(128)  
  , addr   VARCHAR(1024) 
  , CONSTRAINT t1_pk PRIMARY KEY( id )
  , CONSTRAINT t1_uk UNIQUE ( id, name )  
);
COMMIT;



--# result: success
DROP TABLE t1;
COMMIT;

--###################################################
--# CREATE TABLE: with <constraint characteristics>
--###################################################


--# result: success
CREATE TABLE t1 
( 
    id     NUMBER        PRIMARY KEY 
                         NOT DEFERRABLE INITIALLY IMMEDIATE
  , name   VARCHAR(128)  CONSTRAINT t1_nn NOT NULL 
                         DEFERRABLE INITIALLY IMMEDIATE
  , addr   VARCHAR(1024) 
  , CONSTRAINT t1_uk UNIQUE ( id, name ) 
                     DEFERRABLE INITIALLY DEFERRED
);
COMMIT;



--# result: success
DROP TABLE t1;
COMMIT;


--###################################################
--# CREATE TABLE: with <table physical attribute clause>
--###################################################


--# result: success
CREATE TABLE t1 
( 
    id     NUMBER        
  , name   VARCHAR(128)  
  , addr   VARCHAR(1024) 
)
PCTFREE 10 PCTUSED 40
INITRANS 4 MAXTRANS 8
;
COMMIT;



--# result: success
DROP TABLE t1;
COMMIT;


--###################################################
--# CREATE TABLE: with <index physical attribute clause>
--###################################################


--# result: success
CREATE TABLE t1 
( 
    id     NUMBER        
  , name   VARCHAR(128)  
  , addr   VARCHAR(1024) 
  , CONSTRAINT t1_pk PRIMARY KEY( id ) INDEX idx_t1_pk PCTFREE 10 INITRANS 4 MAXTRANS 8
)
;
COMMIT;



--# result: success
DROP TABLE t1;
COMMIT;


--###################################################
--# CREATE TABLE: with <segment attr clause>
--###################################################


--# result: success
CREATE TABLE t1 
( 
    id     NUMBER        
  , name   VARCHAR(128)  
  , addr   VARCHAR(1024) 
)
STORAGE ( INITIAL 10M NEXT 1M MINSIZE 10M MAXSIZE 100M )
;
COMMIT;



--# result: success
DROP TABLE t1;
COMMIT;


--###################################################
--# CREATE TABLE: with <TABLESPACE tablespace_name>
--###################################################


--# result: success
CREATE TABLE t1 
( 
    id     NUMBER        
  , name   VARCHAR(128)  
  , addr   VARCHAR(1024) 
)
TABLESPACE mem_data_tbs
;

COMMIT;



--# result: success
DROP TABLE t1;
COMMIT;


--###################################################
--# CREATE TABLE: with <TABLESPACE index_tablespace_name>
--###################################################


--# result: success
CREATE TABLE t1 
( 
    id     NUMBER        
  , name   VARCHAR(128)  
  , addr   VARCHAR(1024) 
  , CONSTRAINT t1_pk PRIMARY KEY( id ) INDEX idx_t1_pk TABLESPACE mem_temp_tbs
)
;

COMMIT;



--# result: success
DROP TABLE t1;
COMMIT;


--# result: success
CREATE TABLE t1 
( 
    id     NUMBER        
  , name   VARCHAR(128)  
  , addr   VARCHAR(1024) 
  , CONSTRAINT t1_pk PRIMARY KEY( id ) INDEX idx_t1_pk TABLESPACE mem_data_tbs
)
;

COMMIT;



--# result: success
DROP TABLE t1;
COMMIT;


