--###################################################
--# INSERT .. RETURNING INTO: simple example
--###################################################

--# result: success
DROP TABLE IF EXISTS t1;
COMMIT;

--# result: success
CREATE TABLE t1 
( 
    id     NUMBER         GENERATED BY DEFAULT AS IDENTITY
  , name   VARCHAR(128)   DEFAULT 'N/A name'
  , addr   VARCHAR(1024)  DEFAULT 'N/A home'
);
COMMIT;



\var v_id   INTEGER
\var v_name VARCHAR(128)
\var v_data VARCHAR(2048)


--# result: 1 row
--#         1    N/A name
INSERT INTO t1 
       VALUES ( DEFAULT, DEFAULT, DEFAULT )
       RETURNING id, name
       INTO :v_id, :v_name;
COMMIT;


--# result: 1 row
--#         ID: 2, ADDR: N/A home
INSERT INTO t1 
       DEFAULT VALUES
       RETURN 'ID: ' || id || ', ADDR: ' || addr
       INTO :v_data;
COMMIT;





--# result: 2 rows
--#      1    N/A name    N/A home
--#      2    N/A name    N/A home
SELECT * FROM t1;


--# result: success
DROP TABLE t1;
COMMIT;

