--###################################################
--# TRUNCATE TABLE: simple example
--###################################################

--# result: success
DROP TABLE IF EXISTS t1;
COMMIT;



--# result: success
CREATE TABLE t1 
( 
    id     NUMBER
  , data   VARCHAR(128) 
);
COMMIT;

--# result: 3 rows
INSERT INTO t1 VALUES ( 1, 'data_1' ),
                      ( 2, 'data_2' ),
                      ( 3, 'data_3' );
COMMIT;



--# result: 3 rows
--#     1   data_1
--#     2   data_2
--#     3   data_3
SELECT id, data FROM t1 ORDER BY 1;



--# result: success
TRUNCATE TABLE t1;
COMMIT;



--# result: no rows
SELECT id, data FROM t1 ORDER BY 1;



--# result: success
DROP TABLE t1;
COMMIT;


--###################################################
--# TRUNCATE TABLE: with <table_name>
--###################################################

--# result: success
DROP TABLE IF EXISTS t1;
COMMIT;



--# result: success
CREATE TABLE t1 
( 
    id     NUMBER
  , data   VARCHAR(128) 
);
COMMIT;


--# result: success
TRUNCATE TABLE public.t1;
COMMIT;




--# result: success
DROP TABLE t1;
COMMIT;




--###################################################
--# TRUNCATE TABLE: with <RESTART IDENTITY>
--###################################################

--# result: success
DROP TABLE IF EXISTS t1;
COMMIT;


--# result: success
CREATE TABLE t1 
( 
    id     NUMBER        GENERATED BY DEFAULT AS IDENTITY
  , data   VARCHAR(128) 
);
COMMIT;


--# result: 3 rows
INSERT INTO t1 VALUES ( DEFAULT, 'data_A' ),
                      ( DEFAULT, 'data_B' ),
                      ( DEFAULT, 'data_C' );
COMMIT;


--# result: 3 rows
--#     1   data_A
--#     2   data_B
--#     3   data_C
SELECT id, data FROM t1 ORDER BY 1;



--# result: success
TRUNCATE TABLE t1 RESTART IDENTITY;
COMMIT;




--# result: 3 rows
INSERT INTO t1 VALUES ( DEFAULT, 'data_A' ),
                      ( DEFAULT, 'data_B' ),
                      ( DEFAULT, 'data_C' );
COMMIT;



--# result: 3 rows
--#     1   data_A
--#     2   data_B
--#     3   data_C
SELECT id, data FROM t1 ORDER BY 1;



--# result: success
DROP TABLE t1;
COMMIT;



--###################################################
--# TRUNCATE TABLE: with <CONTINUE IDENTITY>
--###################################################

--# result: success
DROP TABLE IF EXISTS t1;
COMMIT;


--# result: success
CREATE TABLE t1 
( 
    id     NUMBER        GENERATED BY DEFAULT AS IDENTITY
  , data   VARCHAR(128) 
);
COMMIT;


--# result: 3 rows
INSERT INTO t1 VALUES ( DEFAULT, 'data_A' ),
                      ( DEFAULT, 'data_B' ),
                      ( DEFAULT, 'data_C' );
COMMIT;


--# result: 3 rows
--#     1   data_A
--#     2   data_B
--#     3   data_C
SELECT id, data FROM t1 ORDER BY 1;



--# result: success
TRUNCATE TABLE t1 CONTINUE IDENTITY;
COMMIT;




--# result: 3 rows
INSERT INTO t1 VALUES ( DEFAULT, 'data_A' ),
                      ( DEFAULT, 'data_B' ),
                      ( DEFAULT, 'data_C' );
COMMIT;



--# result: 3 rows
--#     4   data_A
--#     5   data_B
--#     6   data_C
SELECT id, data FROM t1 ORDER BY 1;



--# result: success
DROP TABLE t1;
COMMIT;



--###################################################
--# TRUNCATE TABLE: with < [DROP STORAGE | DROP ALL STORAGE ]>
--###################################################

--# result: success
DROP TABLE IF EXISTS t1;
COMMIT;


--# result: success
CREATE TABLE t1 
( 
    id     NUMBER        
  , data   VARCHAR(128) 
);
COMMIT;


--# result: success
TRUNCATE TABLE t1 DROP STORAGE;
COMMIT;


--# result: success
TRUNCATE TABLE t1 DROP ALL STORAGE;
COMMIT;



--# result: success
DROP TABLE t1;
COMMIT;
