--###################################################
--# INSERT: simple example
--###################################################

--# result: success
DROP TABLE IF EXISTS t1;
COMMIT;

--# result: success
CREATE TABLE t1 
( 
    id     NUMBER
  , name   VARCHAR(128) 
  , addr   VARCHAR(1024) 
);
COMMIT;


--# result: 1 row
INSERT INTO t1 VALUES ( 1, 'anonymous', 'unknown' );
COMMIT;


--# result: 1 row
INSERT INTO t1 VALUES ( 2, 'someone', 'somewhere' );
COMMIT;


--# result: 1 row
INSERT INTO t1 VALUES ( 3, 'leekmo', 'leekmo''s home' );
COMMIT;


--# result: 3 rows
--#      1    anonymous   unknown
--#      2    someone     somewhere
--#      3    leekmo      leekmo's home
SELECT * FROM t1;



--# result: success
DROP TABLE t1;
COMMIT;



--###################################################
--# INSERT: with <table_name>
--###################################################

--# result: success
DROP TABLE IF EXISTS t1;
COMMIT;

--# result: success
CREATE TABLE t1 
( 
    id     NUMBER
  , name   VARCHAR(128) 
  , addr   VARCHAR(1024) 
);
COMMIT;


--# result: 1 row
INSERT INTO public.t1 VALUES ( 1, 'anonymous', 'unknown' );
COMMIT;


--# result: 1 row
INSERT INTO t1 VALUES ( 2, 'someone', 'somewhere' );
COMMIT;


--# result: 1 row
INSERT INTO public.t1 VALUES ( 3, 'leekmo', 'leekmo''s home' );
COMMIT;


--# result: 3 rows
--#      1    anonymous   unknown
--#      2    someone     somewhere
--#      3    leekmo      leekmo's home
SELECT * FROM t1;



--# result: success
DROP TABLE t1;
COMMIT;



--###################################################
--# INSERT: with < ( column_name [, ...] ) >
--###################################################

--# result: success
DROP TABLE IF EXISTS t1;
COMMIT;

--# result: success
CREATE TABLE t1 
( 
    id     NUMBER
  , name   VARCHAR(128) 
  , addr   VARCHAR(1024) 
);
COMMIT;


--# result: 1 row
INSERT INTO t1 ( id, name, addr ) VALUES ( 1, 'anonymous', 'unknown' );
COMMIT;


--# result: 1 row
INSERT INTO t1 ( name, addr ) VALUES ( 'someone', 'somewhere' );
COMMIT;


--# result: 1 row
INSERT INTO t1 ( id, name ) VALUES ( 3, 'leekmo' );
COMMIT;


--# result: 3 rows
--#      1    anonymous   unknown
--#   null    someone     somewhere
--#      3    leekmo      null
SELECT * FROM t1;



--# result: success
DROP TABLE t1;
COMMIT;




--###################################################
--# INSERT: with <DEFAULT>
--###################################################

--# result: success
DROP TABLE IF EXISTS t1;
COMMIT;

--# result: success
CREATE TABLE t1 
( 
    id     NUMBER         GENERATED BY DEFAULT AS IDENTITY
  , name   VARCHAR(128)   DEFAULT 'N/A'
  , addr   VARCHAR(1024)  DEFAULT 'N/A'
);
COMMIT;





--# result: 1 row
INSERT INTO t1 VALUES ( DEFAULT, 'anonymous', 'unknown' );
COMMIT;


--# result: 1 row
INSERT INTO t1 VALUES ( 2, DEFAULT, 'somewhere' );
COMMIT;


--# result: 1 row
INSERT INTO t1 VALUES ( 3, 'leekmo', DEFAULT );
COMMIT;


--# result: 3 rows
--#      1    anonymous   unknown
--#      2    N/A         somewhere
--#      3    leekmo      N/A
SELECT * FROM t1;



--# result: success
DROP TABLE t1;
COMMIT;



--###################################################
--# INSERT: with <DEFAULT VALUES>
--###################################################

--# result: success
DROP TABLE IF EXISTS t1;
COMMIT;

--# result: success
CREATE TABLE t1 
( 
    id     NUMBER         GENERATED BY DEFAULT AS IDENTITY
  , name   VARCHAR(128)   DEFAULT 'N/A name'
  , addr   VARCHAR(1024)  DEFAULT 'N/A home'
);
COMMIT;





--# result: 1 row
INSERT INTO t1 DEFAULT VALUES;
COMMIT;


--# result: 1 row
INSERT INTO t1 VALUES ( DEFAULT, DEFAULT, DEFAULT );
COMMIT;


--# result: 1 row
INSERT INTO t1 DEFAULT VALUES;
COMMIT;


--# result: 3 rows
--#      1    N/A name    N/A home
--#      2    N/A name    N/A home
--#      3    N/A name    N/A home
SELECT * FROM t1;



--# result: success
DROP TABLE t1;
COMMIT;


--###################################################
--# INSERT: with <multi values>
--###################################################

--# result: success
DROP TABLE IF EXISTS t1;
COMMIT;

--# result: success
CREATE TABLE t1 
( 
    id     NUMBER
  , name   VARCHAR(128) 
  , addr   VARCHAR(1024) 
);
COMMIT;


--# result: 3 rows
INSERT INTO t1 VALUES ( 1, 'anonymous', 'unknown' ),
                      ( 2,   'someone', 'somewhere' ),
                      ( 3,    'leekmo', 'leekmo''s home' );
COMMIT;


--# result: 3 rows
--#      1    anonymous   unknown
--#      2    someone     somewhere
--#      3    leekmo      leekmo's home
SELECT * FROM t1;



--# result: success
DROP TABLE t1;
COMMIT;





--###################################################
--# INSERT: with <from subquery>
--###################################################

--# result: success
DROP TABLE IF EXISTS t1;
DROP TABLE IF EXISTS t2;
COMMIT;

--# result: success
CREATE TABLE t1 
( 
    id     NUMBER
  , name   VARCHAR(128) 
  , addr   VARCHAR(1024) 
);
COMMIT;


--# result: 3 rows
INSERT INTO t1 VALUES ( 1, 'anonymous', 'unknown' ),
                      ( 2,   'someone', 'somewhere' ),
                      ( 3,    'leekmo', 'leekmo''s home' );
COMMIT;


--# result: success
CREATE TABLE t2 
( 
    id     NUMBER
  , name   VARCHAR(128) 
);
COMMIT;


--# 3 rows
INSERT INTO t2( id, name ) 
       SELECT id, name FROM t1;
COMMIT;


--# result: 3 rows
--#      1    anonymous
--#      2    someone  
--#      3    leekmo   
SELECT * FROM t2;



--# result: success
DROP TABLE t1;
DROP TABLE t2;
COMMIT;


