--###################################################
--# INSERT .. RETURNING query: simple example
--###################################################

--# result: success
DROP TABLE IF EXISTS t1;
COMMIT;

--# result: success
CREATE TABLE t1 
( 
    id     NUMBER         GENERATED BY DEFAULT AS IDENTITY
  , name   VARCHAR(128)   DEFAULT 'N/A name'
  , addr   VARCHAR(1024)  DEFAULT 'N/A home'
);
COMMIT;





--# result: 1 row
--#         1    N/A name
INSERT INTO t1 
       VALUES ( DEFAULT, DEFAULT, DEFAULT )
       RETURNING id, name;
COMMIT;


--# result: 1 row
--#         2    N/A home
INSERT INTO t1 
       DEFAULT VALUES
       RETURN id, addr;
COMMIT;


--# result: 2 rows
--#      1    N/A name    N/A home
--#      2    N/A name    N/A home
SELECT * FROM t1;


--# result: success
DROP TABLE t1;
COMMIT;


--###################################################
--# INSERT .. RETURNING query: with <from subquery>
--###################################################

--# result: success
DROP TABLE IF EXISTS t1;
DROP TABLE IF EXISTS t2;
COMMIT;

--# result: success
CREATE TABLE t1 
( 
    id     NUMBER
  , name   VARCHAR(128) 
  , addr   VARCHAR(1024) 
);
COMMIT;


--# result: 3 rows
INSERT INTO t1 VALUES ( 1, 'anonymous', 'unknown' ),
                      ( 2,   'someone', 'somewhere' ),
                      ( 3,    'leekmo', 'leekmo''s home' );
COMMIT;


--# result: success
CREATE TABLE t2 
( 
    id     NUMBER
  , name   VARCHAR(128) 
);
COMMIT;


--# 3 rows
--#      1    anonymous
--#      2    someone  
--#      3    leekmo   
INSERT INTO t2( id, name ) 
       SELECT id, name FROM t1
       RETURNING id, name;
COMMIT;




--# result: success
DROP TABLE t1;
DROP TABLE t2;
COMMIT;


--###################################################
--# INSERT .. RETURNING query: with <value expression>
--###################################################

--# result: success
DROP TABLE IF EXISTS t1;
COMMIT;

--# result: success
CREATE TABLE t1 
( 
    id     NUMBER
  , name   VARCHAR(128) 
  , addr   VARCHAR(1024) 
);
COMMIT;


--# result: 1 rows
--#        1001 
INSERT INTO t1 
       VALUES ( 1, 'anonymous', 'unknown' )
       RETURNING id + 1000 AS id_1000;


--# result: success
DROP TABLE t1;
COMMIT;

