--######################################################################################
-- View For Statement
--
-- MEMBER_NAME     : Cluster Member Name
-- STAT_BEGIN_TIME : Begin Time of Statement
-- USER_NAME       : User Name
-- USER_ID         : Session Identifier
-- USER_SERIAL     : Session Serial
-- CHARSET         : Session Charset
-- PROGRAM         : Program Name
-- USER_LOGIN_TIME : User Login Time
-- SQL_TEXT        : SQL Text
--
--gSQL> SELECT * FROM TECH_STATEMENT;
--
--MEMBER_NAME STAT_BEGIN_TIME            USER_NAME USER_ID USER_SERIAL CHARSET PROGRAM USER_LOGIN_TIME            SQL_TEXT                    
------------- -------------------------- --------- ------- ----------- ------- ------- -------------------------- ----------------------------
--G1N1        2018-08-08 16:38:08.427307 SYS             4           1 UTF8    gsql    2018-08-08 15:26:42.502763 SELECT * FROM TECH_STATEMENT
--######################################################################################

DROP VIEW IF EXISTS PERFORMANCE_VIEW_SCHEMA.TECH_STATEMENT;

CREATE VIEW PERFORMANCE_VIEW_SCHEMA.TECH_STATEMENT
(
  MEMBER_NAME,
  STAT_BEGIN_TIME,
  USER_NAME,
  USER_ID,
  USER_SERIAL,
  CHARSET,
  PROGRAM,
  USER_LOGIN_TIME,
  SQL_TEXT
)
AS
SELECT
  NVL(XST.CLUSTER_MEMBER_NAME, 'STANDALONE') MEMBER_NAME,
  XST.START_TIME STAT_BEGIN_TIME,
  AU.AUTHORIZATION_NAME USER_NAME,
  XSE.ID USER_ID,
  XSE.SERIAL USER_SERIAL,
  XSE.CLIENT_CHARSET CHARSET,
  XSE.PROGRAM PROGRAM,
  XSE.LOGON_TIME USER_LOGIN_TIME,
  XST.SQL_TEXT SQL_TEXT
FROM
  AUTHORIZATIONS@GLOBAL[IGNORE_INACTIVE_MEMBER] AU,
  X$SESSION@GLOBAL[IGNORE_INACTIVE_MEMBER] XSE,
  X$STATEMENT@GLOBAL[IGNORE_INACTIVE_MEMBER] XST
WHERE
  1 = 1 AND
  NVL(AU.CLUSTER_MEMBER_NAME, 'STANDALONE') = NVL(XSE.CLUSTER_MEMBER_NAME, 'STANDALONE') AND
  NVL(AU.CLUSTER_MEMBER_NAME, 'STANDALONE') = NVL(XST.CLUSTER_MEMBER_NAME, 'STANDALONE') AND
  NVL(XSE.CLUSTER_MEMBER_NAME, 'STANDALONE') = NVL(XST.CLUSTER_MEMBER_NAME, 'STANDALONE') AND
  AU.AUTH_ID = XSE.USER_ID AND
  XSE.ID = XST.SESSION_ID AND
  XSE.PROGRAM != 'cluster peer'
ORDER BY 2
;

GRANT SELECT ON PERFORMANCE_VIEW_SCHEMA.TECH_STATEMENT TO PUBLIC;